aws/copilot-cli

internal/pkg/archer/workspace.go, internal/pkg/cli/init.go, internal/pkg/cli/init_test.go, internal/pkg/cli/mocks/mock_prompter.go, internal/pkg/cli/prompter.go, internal/pkg/store/ssm/ssm.go, internal/pkg/term/color/color.go, internal/pkg/term/prompt/prompt.go, internal/pkg/term/prompt/prompt_test.go, internal/pkg/workspace/workspace.go, internal/pkg/workspace/workspace_test.go, mocks/mock_workspace.go
=> Log descriptive message between actions in Init

.dependabot/config.yml
Now that we know this works, change it to weekly updates.
=> Change dependabot updates to weekly

internal/pkg/store/ssm/ssm.go, internal/pkg/store/ssm/ssm_integration_test.go, internal/pkg/store/ssm/ssm_test.go
Specifically, the `ListEnvironments` and `ListProjects` methods.
Fixes #65.
=> Implement pagination for the SSM store

internal/pkg/aws/session/session.go, internal/pkg/cli/env_add.go, internal/pkg/cli/init.go, internal/pkg/store/ssm/ssm.go
Consolidate session creations.
#165 
=> Consolidate AWS session creation

internal/pkg/deploy/cloudformation/changeset.go, internal/pkg/deploy/cloudformation/cloudformation.go
=> Add tags to environment

STYLE_GUIDE.md
=> Add "Recommended actions" to style guide

internal/pkg/manifest/app_manifest.go, internal/pkg/manifest/app_manifest_test.go, internal/pkg/manifest/errors.go
This is needed so that we can add pipeline manifest related functionalities.
Fixes #217 
=> Rename some functions & variables

templates/cicd/manifest.yml
Want to get some feedback before implementing the data model in Go.
Part of #210.
=> Preliminary template for the pipeline manifest

templates/environment/cf.yml, templates/lb-fargate-service/cf.yml
Resolves #201
First pass! Generated a template with https://play.golang.org/p/irSWlrmE8Vt 
We still need to add autoscaling, alarms, dashboards, outputs  ...
=> CFN template for LB Web Applications

templates/lb-fargate-service/cf.yml
✅ Tested by deploying the CFN template.
=> Remove ProjectName, EnvName, AppName prefix from logical ids

internal/pkg/archer/workspace.go, internal/pkg/workspace/workspace.go, internal/pkg/workspace/workspace_test.go, mocks/mock_workspace.go
We need a list of local applications in order to build a pipeline for the workspace.
Closes #233.
=> Add LocalApps() into the Workspace interface

internal/pkg/cli/app.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go
=> Skeleton for the "app package" command

internal/pkg/manifest/app_manifest.go, internal/pkg/manifest/app_manifest_test.go, internal/pkg/manifest/lb_fargate_manifest.go, internal/pkg/manifest/lb_fargate_manifest_test.go, templates/lb-fargate-service/manifest.yml
=> Update the manifest template for "Load Balanced Web App"

templates/lb-fargate-service/params.json
=> Add template configuration file for LBFargateService

internal/pkg/workspace/workspace.go, internal/pkg/workspace/workspace_test.go
=> Rename Service to Workspace

internal/pkg/cli/app.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/deploy/cloudformation/lb_fargate_app.go
Retrieve the inputs for https://github.com/aws/amazon-ecs-cli-v2/issues/229
=> Implement Ask and Validate methods for PackageAppOpts

cmd/archer/main.go, internal/pkg/cli/group/group.go, internal/pkg/cli/group/group_windows.go, internal/pkg/cli/pipeline.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
=> Scaffold for Pipeline commands

internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/cli.go, internal/pkg/deploy/cloudformation/lb_fargate_app.go, internal/pkg/deploy/cloudformation/lb_fargate_app_test.go
=> Writes templates to directory if --output-dir is set

internal/pkg/cli/init.go
=> Add identity dependency to ProjectOpts in "init" cmd

internal/pkg/cli/app_package.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go
=> Move LBFargateStackConfig to stack pkg

internal/pkg/archer/project.go
This interface describes the methods to fetch resources for a particular
project.
=> Add ProjectResourceStore interface

internal/pkg/cli/app_package.go, internal/pkg/cli/mocks/mock_prompter.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go, internal/pkg/cli/prompter.go, internal/pkg/term/prompt/prompt.go
=> Pipeline command, part the first

internal/pkg/deploy/cloudformation/project.go
This is necessary because we would like to reuse the same helper function when adding project level resources for the archer CodePipeline.
Closes #306.
=> Decouple addNewProjectStackInstances() from archer environment

internal/pkg/cli/deploy.go, internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/cli/init.go, internal/pkg/cli/mocks/mock_deploy.go, internal/pkg/deploy/cloudformation/cloudformation_integration_test.go, internal/pkg/deploy/cloudformation/project.go, internal/pkg/term/progress/spinner.go, internal/pkg/term/progress/spinner_test.go, templates/environment/cf.yml
=> Create a stackset instance on new environment 

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_deploy_test.go
Source applications available to deploy from the workspace instead of SSM.
#291 
=> Limit app deploy to apps in the workspace

internal/pkg/deploy/cloudformation/stack/pipeline.go, internal/pkg/deploy/cloudformation/stack/pipeline_test.go
=> Move pipeline files into stack pkg

STYLE_GUIDE.md, cmd/archer/main.go, cmd/archer/template/macro.go, cmd/archer/template/template.go, cmd/archer/template/template_windows.go, internal/pkg/cli/app.go, internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_package.go, internal/pkg/cli/completion.go, internal/pkg/cli/env.go, internal/pkg/cli/env_init.go, internal/pkg/cli/flag.go, internal/pkg/cli/group/group.go, internal/pkg/cli/init.go, internal/pkg/cli/pipeline.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/project.go, internal/pkg/cli/project_init.go, internal/pkg/cli/project_list.go, internal/pkg/cli/version.go, internal/pkg/term/color/color.go, internal/pkg/term/log/log.go
* Propose new guideline on _screen size_ in the style guide.
* Archer now displays text nicely on white background terminal screens.
* Move all flags to constants.
* Add a period '.' at the end of command descriptions.
=> Add UX improvements 👩‍🎨

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/deploy.go, internal/pkg/cli/mocks/mock_deploy.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go, internal/pkg/deploy/deploy.go
=> Add a ImageRepoURL field to CreateLBFargateAppInput

internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/deploy.go, internal/pkg/cli/init.go, internal/pkg/cli/mocks/mock_deploy.go, internal/pkg/deploy/cloudformation/cloudformation_integration_test.go, internal/pkg/deploy/cloudformation/project.go, internal/pkg/deploy/cloudformation/project_test.go, internal/pkg/store/ssm/ssm.go
=> Create application's repository in archer init

internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go
=> Append Dockerfile name to selections on app init

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_deploy_test.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go
* Remove Custom path option in `app init` workflow
* Remove `/Dockerfile` from selection in `app init` workflow
* Added invalid input values to error messages in `app deploy` workflow
#330 
#328 
=> Remove Dockerfile selection option

internal/pkg/archer/workspace.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go, internal/pkg/workspace/workspace.go, internal/pkg/workspace/workspace_test.go, mocks/mock_workspace.go
Write to `pipeline.yml` instead of `pipeline-<project>-<repo>.yml`
=> Rename pipeline manifest file

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_deploy_test.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/cli.go, internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/cli/env_list.go, internal/pkg/cli/env_list_test.go, internal/pkg/cli/init.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
=> Add prompt to GlobalOpts

internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml, templates/cicd/buildspec.yml, templates/cicd/pipeline_cfn.yml
=> Add builspec that generates cfn templates and pushes images to ECR

internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go, internal/pkg/workspace/workspace.go
=> Write buildspec.yml to project directory

internal/pkg/deploy/cloudformation/cloudformation.go, internal/pkg/deploy/cloudformation/cloudformation_test.go, internal/pkg/deploy/cloudformation/env.go, internal/pkg/deploy/cloudformation/env_test.go, internal/pkg/deploy/cloudformation/stack/env.go, internal/pkg/deploy/cloudformation/stack/env_test.go
=> Restructure deploy logic for env for consistency

internal/pkg/aws/session/session.go, internal/pkg/build/docker/docker.go, internal/pkg/build/ecr/ecr.go, internal/pkg/build/ecr/ecr_test.go, internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_deploy_test.go
* Remove CreateRepository functionality from `ecr` package and `app deploy` flow
* Added `DefaultWithRegion` function to `session` package
* Modified `docker` package to make it mockable
* Revised client configurations for `app deploy` flow
#292 
=> Remove ECR repo creation in app deploy flow

internal/pkg/cli/deploy.go, internal/pkg/cli/flag.go, internal/pkg/cli/mocks/mock_deploy.go, internal/pkg/cli/pipeline.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_update.go, internal/pkg/cli/validate.go, internal/pkg/cli/validate_test.go, internal/pkg/deploy/cloudformation/pipeline.go, internal/pkg/deploy/cloudformation/project_test.go, internal/pkg/deploy/cloudformation/stack/pipeline.go, internal/pkg/deploy/cloudformation/stack/pipeline_test.go, internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml, internal/pkg/deploy/pipeline.go, internal/pkg/deploy/pipeline_test.go, internal/pkg/manifest/pipeline.go, templates/cicd/pipeline_cfn.yml
This PR DOES:
- deploy the pipeline.yml
this PR DOES NOT:
- deploy a pipeline that actually works
Fast follow: Ensure role name does not exceed 64 characters, but submitting this to get early feedback. 
=> Pipeline update

internal/pkg/cli/pipeline_update.go, internal/pkg/manifest/pipeline.go
=> Remove unnecessary account field

internal/pkg/archer/env.go, internal/pkg/deploy/cloudformation/stack/env.go, internal/pkg/deploy/cloudformation/stack/env_test.go
=> Add the manager role ARN as a field to an environment struct

internal/pkg/aws/identity/identity.go, internal/pkg/aws/identity/identity_test.go, internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/deploy/cloudformation/cloudformation_integration_test.go, internal/pkg/deploy/cloudformation/pipeline.go, internal/pkg/deploy/cloudformation/pipeline_integration_test.go, internal/pkg/deploy/cloudformation/stack/project.go, internal/pkg/deploy/cloudformation/stack/project_test.go, internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml, internal/pkg/deploy/pipeline.go, templates/cicd/pipeline_cfn.yml
Added an integration test as well to ensure we can properly spin up a pipeline that itself is hosted in one AWS region while deploying to another region. 
Closes #341.
=> Integrate with resources created via project stackset and env

internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml, templates/cicd/pipeline_cfn.yml
This is necessary because archer CLI needs access to these services while it runs in the build stage.
Closes #377
=> Add more permissions to the Build role

internal/pkg/cli/pipeline_update.go, internal/pkg/cli/pipeline_update_test.go
=> Add unit tests for pipeline update

internal/pkg/store/store_integration_test.go
=> Fix SSM Integration Tests

internal/pkg/build/docker/docker.go, internal/pkg/build/docker/docker_test.go
=> Add unit tests to docker package

internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go, internal/pkg/store/secretsmanager/secretsmanager.go
=> Don't fail pipeline init if github token secret exists

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_package.go, internal/pkg/cli/cli.go, internal/pkg/cli/completion.go, internal/pkg/cli/env.go, internal/pkg/cli/env_delete.go, internal/pkg/cli/env_delete_test.go, internal/pkg/cli/env_init.go, internal/pkg/cli/env_list.go, internal/pkg/cli/flag.go, internal/pkg/cli/init.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_update.go, internal/pkg/cli/project_init.go, internal/pkg/cli/project_list.go, internal/pkg/cli/version.go
Basic skeleton for the `"env delete"` command.
=> Skeleton for "env delete" cmd

internal/pkg/deploy/cloudformation/stack/project.go
I used the wrong key and didn't run the integration tests.
🔔 Shame on me 🔔 
I've run them now.
=> Fix deploy project infrastructure

templates/environment/cf.yml
The env manager role needs more permissions to actually function.
Fixes #378.
=> Added more permissions to the env manager role

internal/pkg/deploy/cloudformation/stack/testdata/rendered_pipeline_cfn_template.yml, templates/cicd/pipeline_cfn.yml
Added necessary permission to push to ECR
Fixes #418.
=> Missing ecr permission

internal/pkg/deploy/cloudformation/stack/testdata/rendered_pipeline_cfn_template.yml, templates/cicd/pipeline_cfn.yml
Currently integ test actions in the pipeline fail with ```[Container] 2019/11/20 01:11:31 Waiting for agent ping
[Container] 2019/11/20 01:11:33 Waiting for DOWNLOAD_SOURCE```.
This fixes #423.
=> Made the integ test action runs in the pipeline

internal/pkg/cli/env_list.go, internal/pkg/cli/env_list_test.go, internal/pkg/cli/flag.go, templates/cicd/buildspec.yml
=> Retrieves environments using --json in buildspec

internal/pkg/cli/init.go, internal/pkg/store/app.go, internal/pkg/store/env.go, internal/pkg/term/log/log_test.go, internal/pkg/term/log/prefix.go, internal/pkg/term/log/prefix_windows.go
* Fixes #436 
* Also improves init experience by removing verbose text
=> Pass the app name before invoking deploy in "init"

internal/pkg/cli/init.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_update.go
Small PR adding missing comments for some exported functions.
=> Add missing comments for exported functions

internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
=> Stop continue asking for more env to add when there's no more

internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
=> Remove .git at the end of the Github URL

go.mod, go.sum, internal/pkg/term/progress/spinner.go
Fixes #435 (see issue for detailed explanation)
=> Fix windows spinner not replacing existing line

Makefile, internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/cli/progress.go, templates/environment/cf.yml, templates/lb-fargate-service/cf.yml
The LBFargateWebApp tasks will be launched in the public subnets.
=> Remove NAT gateways from environment template

internal/pkg/cli/pipeline_update.go, internal/pkg/cli/pipeline_update_test.go
=> Add error catch when executing pipeline deploy

internal/pkg/aws/session/session.go, internal/pkg/cli/env_delete.go, internal/pkg/cli/env_delete_test.go, internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/cli/init.go, internal/pkg/cli/mocks/mock_prompter.go, internal/pkg/cli/prompter.go, internal/pkg/deploy/cloudformation/env.go, internal/pkg/deploy/cloudformation/env_test.go, internal/pkg/term/prompt/prompt.go, templates/environment/cf.yml
Resolves https://github.com/aws/amazon-ecs-cli-v2/issues/459
=> Use a named profile to delete environments

internal/pkg/deploy/cloudformation/cloudformation.go, internal/pkg/deploy/cloudformation/cloudformation_test.go, internal/pkg/deploy/cloudformation/errors.go, internal/pkg/deploy/cloudformation/pipeline.go, internal/pkg/deploy/cloudformation/pipeline_test.go
=> Stop waiting for pipeline update completion if there are no updates

internal/pkg/cli/init.go, internal/pkg/cli/init_test.go
=> Improve wording within init cmd

internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go, templates/lb-fargate-service/cf.yml, templates/lb-fargate-service/params.json
=> Remove unused RulePriority template parameter

internal/pkg/deploy/cloudformation/stack/testdata/rendered_pipeline_cfn_template.yml, templates/cicd/pipeline_cfn.yml
Remove the integration tests from the pipeline for now because we want to introduce a better user experience by #443, #476 and #477
This PR implements $478.
=> Temporarily remove integration test actions from pipeline stages

internal/pkg/manifest/pipeline_test.go, templates/cicd/pipeline.yml
=> Remove some extra whitespaces

internal/pkg/cli/app.go, internal/pkg/cli/app_list.go, internal/pkg/cli/app_list_test.go, internal/pkg/cli/flag.go
Fix #439. And change `archer env ls` command's prompt from "inputting project name" to "selecting projects".
=> Add archer app ls command

.dockerignore, Dockerfile, Makefile
Retrieve the binaries from a container.
=> Add release-docker target to retrieve binaries from a container

internal/pkg/deploy/cloudformation/stack/testdata/rendered_project_cfn_template.yml, templates/project/cf.yml
=> Don't retain the bucket when the stack instance is deleted

internal/pkg/manifest/lb_fargate_manifest_test.go, templates/lb-fargate-service/manifest.yml
The page doesn't exist at the moment so we'll remove the link for now. We can re-add it once the page exists.
=> Update link to docs from web app manifest

internal/pkg/cli/flag.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
=> Allow customized branch name for pipeline GitHub repository

internal/pkg/deploy/cloudformation/pipeline_integration_test.go
Also fixed broken integration test.
This PR resolves #488.
=> Create mock secret in Secrets Manager.

internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/dockerfile.go, internal/pkg/cli/dockerfile_test.go, internal/pkg/cli/init.go, internal/pkg/cli/validate.go, internal/pkg/cli/validate_test.go
=> Improve error when no Dockerfile found and no flag pass

internal/pkg/describe/mocks/mock_describe.go, internal/pkg/describe/webapp_test.go
Running `make gen-mocks` was resulting in some mock changes in the `describe` package. This PR commits all the latest mocks and updates affected tests.
=> Add missed mock_describe.go changes

internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
Previously the buildspec was written to the workspace folder, which was incorrect. 
Fixes #514
=> Write integration test buildspec to each app's folder

internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/dockerfile.go, internal/pkg/cli/dockerfile_test.go, internal/pkg/cli/flag.go, internal/pkg/cli/init.go
=> Add validation for app init dockerfile path flag with no dockerfile

internal/pkg/cli/flag.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
Branches are a git concept, not unique to GitHub. This also makes it
more generic when we add other options for the pipeline source stage.
=> Rename GitHubBranch to GitBranch

go.sum, internal/pkg/deploy/cloudformation/pipeline_integration_test.go
=> Update testGithubSecret reference

Makefile
=> Bump integration test timeout from 30m to 60m

Makefile
=> Update release artifact bucket name

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/git.go
=> Defer and consolidate git describe commands

internal/pkg/cli/app_show.go, internal/pkg/cli/app_show_test.go, internal/pkg/cli/cli.go, internal/pkg/cli/mocks/mock_cli.go, internal/pkg/describe/webapp.go, internal/pkg/describe/webapp_test.go
Fix #538. Added deploy information to app show subcommand.
=> feat: add deploy information to app show subcommand

internal/pkg/cli/app_list.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go
Refactoring our commands to follow Validate -> Ask -> Execute.
=> Validate before asking for flags in app package

internal/pkg/cli/app_show.go, internal/pkg/cli/app_show_test.go, internal/pkg/cli/cli.go, internal/pkg/cli/flag.go, internal/pkg/cli/mocks/mock_cli.go, internal/pkg/describe/mocks/mock_describe.go, internal/pkg/describe/webapp.go, internal/pkg/describe/webapp_test.go, internal/pkg/term/color/color.go
=> fix: change app show output and refactor validate and ask

internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go
Call `Validate` first, then `Ask`, then `Execute`.
=> refactor(env init): conform to Validate, Ask, Execute

internal/pkg/cli/app_show.go, internal/pkg/cli/app_show_test.go, internal/pkg/cli/env_list.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_update.go, internal/pkg/cli/project_init.go, internal/pkg/cli/project_init_test.go, internal/pkg/describe/webapp.go
All commands have `RunE` to be only `Validate() -> Ask() -> Execute()`!
=> Remaining commands conform to Validate, Ask, Execute

internal/pkg/cli/app_show.go, internal/pkg/cli/app_show_test.go, internal/pkg/cli/project.go, internal/pkg/cli/project_show.go, internal/pkg/cli/project_show_test.go, internal/pkg/describe/project.go, internal/pkg/describe/webapp.go
=> feat(project-show): add project show

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/app_list.go, internal/pkg/cli/app_list_test.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/app_show.go, internal/pkg/cli/app_show_test.go, internal/pkg/cli/completion.go, internal/pkg/cli/completion_test.go, internal/pkg/cli/env_delete.go, internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/cli/env_list.go, internal/pkg/cli/env_list_test.go, internal/pkg/cli/init.go, internal/pkg/cli/init_test.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go, internal/pkg/cli/pipeline_update.go, internal/pkg/cli/pipeline_update_test.go, internal/pkg/cli/project_init.go, internal/pkg/cli/project_init_test.go, internal/pkg/cli/project_list.go, internal/pkg/cli/project_list_test.go, internal/pkg/cli/project_show.go, internal/pkg/cli/project_show_test.go
=> refactor: make structs in cli private

internal/pkg/cli/app_delete.go, internal/pkg/cli/app_delete_test.go
=> feat(app delete): ask user to select application instead of writing it

go.mod, internal/pkg/cli/app_show.go, internal/pkg/cli/app_show_test.go
=> feat(app-show): infer app from working directory

internal/pkg/describe/webapp_test.go
Fixes unit test failure (testing the values of an intermediate array with random order).
=> test(describe): quick fix to unittest failure due to random order array

internal/pkg/describe/webapp.go, internal/pkg/describe/webapp_test.go
=> fix(app-show): remove dummy resources

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go, internal/pkg/manifest/app_manifest.go, internal/pkg/manifest/app_manifest_test.go, internal/pkg/manifest/lb_fargate_manifest.go, internal/pkg/manifest/lb_fargate_manifest_test.go, templates/lb-fargate-service/cf.yml
=> improvement(manifest): better default path for multiple apps

internal/pkg/cli/app_package.go, internal/pkg/manifest/lb_fargate_manifest.go, templates/lb-fargate-service/cf.yml
fix #651. Updated to 30 days by default but not expose it to users to configure. Will be addressing in the future.
=> fix(logs): change default logs retention time to 30 days

buildspec-e2e.yml
This is a rough draft at our e2e test buildspec. I want to find
a few better ways to populate the credentials file and run the tests,
but this should get us going.
=> test: add E2E Buildspec

go.sum, internal/pkg/cli/app_delete.go, internal/pkg/cli/app_delete_test.go, internal/pkg/cli/env_delete.go, internal/pkg/cli/env_delete_test.go
=> chore: skip selecting for app/env/profile name if only one found

internal/pkg/cli/app_deploy.go, internal/pkg/cli/pipeline_delete.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go, templates/cicd/buildspec.yml, templates/lb-fargate-service/params.json
=> feat(pipeline): support addons resources for pipeline

README.md
=> docs: update README with v0.0.6 instructions

cf-custom-resources/package-lock.json, cf-custom-resources/package.json
https://github.com/aws/amazon-ecs-cli-v2/network/alert/cf-custom-resources/package-lock.json/minimist/open
=> chore: update NPM dependencies

README.md
=> docs: update README with v0.0.7

.mergify.yml
This change has been made by @efekarakus from https://mergify.io simulator.
---
<details>
<summary>Mergify commands and options</summary>
<br />
More conditions and actions can be found in the [documention](https://doc.mergify.io/).
<br />
<br />
You can also trigger Mergify actions by commenting on this pull request:
- `@Mergifyio refresh` will re-evaluate the rules
- `@Mergifyio rebase` will rebase this PR
- `@Mergifyio backport <destination>` will backport this PR on `<destination>` branch
Additionally, on Mergify [dashboard](https://dashboard.mergify.io/) you can:
- look at your merge queues
- generate the Mergify configuration with the simulator.
Finally, you can contact us on https://mergify.io/
</details>
=> chore: add mergify configuration

internal/pkg/aws/cloudformation/changeset.go, internal/pkg/aws/cloudformation/cloudformation.go
Addresses feedback from https://github.com/aws/amazon-ecs-cli-v2/pull/757
=> refactor(cloudformation): provide constructors for types of change sets

e2e/internal/client/cli.go, internal/pkg/cli/app_show.go, internal/pkg/cli/project_show.go
=> chore!: rename flags for app and project show

internal/pkg/archer/project.go, internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_deploy_test.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/cli/flag.go, internal/pkg/cli/pipeline_update.go, internal/pkg/cli/project_init.go, internal/pkg/cli/project_init_test.go, internal/pkg/deploy/app.go, internal/pkg/deploy/cloudformation/project.go, internal/pkg/deploy/cloudformation/stack/env.go, internal/pkg/deploy/cloudformation/stack/env_test.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go, internal/pkg/deploy/cloudformation/stack/pipeline.go, internal/pkg/deploy/cloudformation/stack/pipeline_test.go, internal/pkg/deploy/cloudformation/stack/project.go, internal/pkg/deploy/cloudformation/stack/project_test.go, internal/pkg/deploy/cloudformation/stack/tags.go, internal/pkg/deploy/env.go, internal/pkg/deploy/pipeline.go, internal/pkg/deploy/project.go, internal/pkg/store/project_test.go, templates/lb-fargate-service/params.json.tmpl
Resolves https://github.com/aws/amazon-ecs-cli-v2/issues/772
=> feat: add --tags flag to project init

internal/pkg/aws/tags/tags.go, internal/pkg/aws/tags/tags_test.go, internal/pkg/cli/app_deploy.go, internal/pkg/cli/project_init.go, internal/pkg/cli/project_init_test.go, internal/pkg/deploy/cloudformation/stack/tags.go
=> feat: add --resource-tags flag to deploy command

cf-custom-resources/lib/alb-rule-priority-generator.js, cf-custom-resources/lib/dns-cert-validator.js, cf-custom-resources/lib/dns-delegation.js, cf-custom-resources/lib/enable-long-arns.js, cf-custom-resources/test/alb-rule-priority-generator-test.js, cf-custom-resources/test/dns-cert-validator-test.js, cf-custom-resources/test/dns-delegation-test.js, cf-custom-resources/test/enable-long-arn-test.js, internal/pkg/aws/ecs/ecs_test.go, internal/pkg/deploy/cloudformation/stack/env.go, internal/pkg/deploy/cloudformation/stack/env_test.go, templates/environment/cf.yml, templates/lb-fargate-service/cf.yml
=> feat!: propagate tags to ECS tasks

internal/pkg/describe/webapp.go, internal/pkg/describe/webapp_test.go
=> feat(cli): add method to get cluster name and service name

internal/pkg/cli/app_delete.go, internal/pkg/cli/app_delete_test.go, internal/pkg/cli/interfaces.go, internal/pkg/cli/mocks/mock_interfaces.go
=> test: add app delete unit tests

internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go
=> fix: do not error on pipeline init for existing buildspec.yml

internal/pkg/cli/pipeline_delete.go, internal/pkg/cli/project_delete.go, internal/pkg/deploy/cloudformation/pipeline.go
=> fix: delete pipeline from project

internal/pkg/cli/env_show.go, internal/pkg/cli/env_show_test.go
Filled in Validate function of `env show` and accompanying tests.
=> feat(cli): env show--Validate

internal/pkg/cli/app_show_test.go
=> refactor: make mocks in app_show_test more consistent

.mergify.yml
=> chore: block mergify if PR has label "do-not-merge"

internal/pkg/cli/env_show.go, internal/pkg/cli/env_show_test.go
Added env show ask method and unit tests.
=> build(cli): env show ask

internal/pkg/cli/app_init_test.go, internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go, internal/pkg/manifest/app.go, internal/pkg/manifest/app_test.go, internal/pkg/manifest/backend_app.go, internal/pkg/manifest/backend_app_test.go, internal/pkg/manifest/errors.go, internal/pkg/manifest/lb_web_app.go, internal/pkg/manifest/lb_web_app_test.go, internal/pkg/manifest/testdata/backend-app-customhealthcheck.yml, templates/applications/backend-app/manifest.yml, templates/applications/lb-web-app/manifest.yml
Note: I've also removed the unused ASG configuration in the lb web app.
=> chore: unmarshal backend app manifest

internal/pkg/cli/project_show_test.go
=> refactor: project show tests

internal/pkg/cli/app_deploy.go
=> feat(cli): app deploy supports backend apps

e2e/multi-app-project/multi_app_project_test.go, e2e/multi-app-project/www/Dockerfile, e2e/multi-app-project/www/go.mod, e2e/multi-app-project/www/main.go, e2e/multi-env-project/multi_env_test.go
=> test(e2e): add backend app type e2e test

internal/pkg/addons/addons.go, internal/pkg/addons/addons_test.go, internal/pkg/addons/errors.go, internal/pkg/addons/mocks/mock_addons.go, internal/pkg/addons/testdata/template.yml, internal/pkg/cli/app_deploy_test.go, templates/addons/cf.yml
Renaming for `addons` package. Will be including a manual test soon.
=> chore(addons): copilot command rename

.mergify.yml
=> chore: update mergify to apply on rename-commands branch

internal/pkg/aws/cloudwatchlogs/cloudwatchlogs.go, internal/pkg/aws/codepipeline/codepipeline.go, internal/pkg/aws/codepipeline/codepipeline_test.go, internal/pkg/aws/ecs/ecs.go, internal/pkg/cli/interfaces.go, internal/pkg/cli/mocks/mock_interfaces.go, internal/pkg/cli/pipeline_show.go, internal/pkg/cli/pipeline_show_test.go
=> refactor(aws): remove project/app concepts from the aws packages

internal/pkg/cli/app_deploy.go, internal/pkg/cli/app_deploy_test.go, internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go, internal/pkg/cli/app_list_test.go, internal/pkg/cli/app_package.go, internal/pkg/cli/app_package_test.go, internal/pkg/cli/app_show.go, internal/pkg/cli/flag.go, internal/pkg/cli/validate.go, internal/pkg/deploy/cloudformation/stack/backend_app.go, internal/pkg/deploy/cloudformation/stack/backend_app_test.go, internal/pkg/deploy/cloudformation/stack/lb_web_app.go, internal/pkg/deploy/cloudformation/stack/lb_web_app_test.go, internal/pkg/describe/backend_app_test.go, internal/pkg/describe/lb_web_app_test.go, internal/pkg/manifest/backend_svc.go, internal/pkg/manifest/backend_svc_test.go, internal/pkg/manifest/errors.go, internal/pkg/manifest/lb_web_svc.go, internal/pkg/manifest/lb_web_svc_test.go, internal/pkg/manifest/pipeline.go, internal/pkg/manifest/svc.go, internal/pkg/manifest/svc_test.go, internal/pkg/manifest/testdata/backend-svc-customhealthcheck.yml, internal/pkg/manifest/testdata/backend-svc-nohealthcheck.yml, templates/services/backend/manifest.yml, templates/services/common/cf/envvars.yml, templates/services/lb-web/manifest.yml
Copilot renaming for `manifest` package.
=> chore(manifest): copilot renaming for manifest pkg

README.md
=> chore: update binaries to v0.0.8

internal/pkg/cli/app_status.go, internal/pkg/cli/app_status_test.go
=> fix(cli): "app status" mentions status instead of logs

README.md
=> docs: update README with v0.0.9

cmd/ecs-preview/main.go, internal/pkg/cli/app.go, internal/pkg/cli/flag.go, internal/pkg/cli/init.go, internal/pkg/cli/interfaces.go, internal/pkg/cli/mocks/mock_interfaces.go, internal/pkg/cli/project_init.go, internal/pkg/cli/project_init_test.go, internal/pkg/cli/project_show.go, internal/pkg/cli/project_show_test.go, internal/pkg/cli/svc.go, internal/pkg/cli/svc_init.go, internal/pkg/cli/svc_init_test.go, internal/pkg/cli/svc_show.go, internal/pkg/cli/validate.go, internal/pkg/cli/validate_test.go
Copilot renaming for `app init`.
=> chore(cli): copilot renaming for app init

internal/pkg/cli/app_list.go, internal/pkg/cli/app_list_test.go, internal/pkg/cli/app_show_test.go, internal/pkg/cli/project.go
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*
=> chore: rename "project ls" to "app ls"

cmd/ecs-preview/main.go, internal/pkg/cli/app.go
=> chore: rename "project" cmd to "app"

internal/pkg/cli/deploy.go, internal/pkg/cli/env_show.go, internal/pkg/cli/flag.go, internal/pkg/cli/interfaces.go, internal/pkg/cli/mocks/mock_interfaces.go, internal/pkg/cli/pipeline_show.go, internal/pkg/cli/svc_list.go, internal/pkg/cli/svc_show.go
Miscellaneous files in the `cli` pkg that needed to be updated to reflect the command rename.
=> chore: update "deploy" cmd, flags, and interfaces 

internal/pkg/cli/pipeline.go, internal/pkg/cli/pipeline_delete.go, internal/pkg/cli/pipeline_delete_test.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_init_test.go, internal/pkg/cli/pipeline_show.go, internal/pkg/cli/pipeline_show_test.go, internal/pkg/cli/pipeline_update.go, internal/pkg/cli/pipeline_update_test.go
=> chore: update "pipeline" cmds to use "applications" and "services"

e2e/multi-svc-app/multi_svc_app_test.go
=> test(e2e): fix multi svc test to expect the proper count

.mergify.yml
=> chore: automerge dependabot PRs with mergify

internal/pkg/addons/addons.go, internal/pkg/addons/addons_test.go, internal/pkg/addons/mocks/mock_addons.go, internal/pkg/deploy/cloudformation/mocks/mock_cloudformation.go, internal/pkg/workspace/workspace.go, internal/pkg/workspace/workspace_test.go
=> chore(workspace): add WriteAddon method and rename ReadAddon method

internal/pkg/addons/addons_test.go, internal/pkg/addons/cloudformation.go, internal/pkg/addons/errors.go, internal/pkg/addons/errors_test.go, internal/pkg/addons/testdata/merge/first.yaml, internal/pkg/addons/testdata/merge/invalid-conditions.yaml, internal/pkg/addons/testdata/merge/second.yaml, internal/pkg/addons/testdata/merge/wanted.yaml
Merges the `Conditions` section of two templates.
Follows the same logic as `Parameters` and `Metadata`.
Related to #994 
=>  chore(addons): merge cfn templates Conditions section

internal/pkg/addons/addons_test.go, internal/pkg/addons/cloudformation.go, internal/pkg/addons/errors.go, internal/pkg/addons/errors_test.go, internal/pkg/addons/testdata/merge/first.yaml, internal/pkg/addons/testdata/merge/invalid-resources.yaml, internal/pkg/addons/testdata/merge/second.yaml, internal/pkg/addons/testdata/merge/wanted.yaml
=> chore(addons): merge cfn templates Resource section

internal/pkg/addons/addons_test.go, internal/pkg/addons/cloudformation.go, internal/pkg/addons/errors.go, internal/pkg/addons/errors_test.go, internal/pkg/addons/testdata/merge/first.yaml, internal/pkg/addons/testdata/merge/invalid-outputs.yaml, internal/pkg/addons/testdata/merge/second.yaml, internal/pkg/addons/testdata/merge/wanted.yaml
=> chore(addons): merge cfn templates Outputs section

internal/pkg/describe/describe.go, internal/pkg/describe/pipeline_test.go, internal/pkg/describe/status.go
=> test(describe): fix flaky pipeline show test

README.md
=> docs: update README for new binary name

CONTRIBUTING.md
=> docs: update CONTRIBUTING.md with copilot terms

CHARTER.md
=> docs: update CHARTER.md with copilot terms

internal/pkg/cli/mocks/mock_identity.go, internal/pkg/cli/mocks/mock_interfaces.go, internal/pkg/cli/mocks/mock_progress.go, internal/pkg/cli/mocks/mock_prompter.go, internal/pkg/deploy/cloudformation/mocks/mock_cloudformation.go, internal/pkg/deploy/cloudformation/stack/mocks/mock_backend_svc.go, internal/pkg/deploy/cloudformation/stack/mocks/mock_lb_web_svc.go, internal/pkg/deploy/deploy.go, internal/pkg/describe/backend_service.go, internal/pkg/describe/backend_service_test.go, internal/pkg/describe/env.go, internal/pkg/describe/env_test.go, internal/pkg/describe/lb_web_service.go, internal/pkg/describe/lb_web_service_test.go, internal/pkg/describe/mocks/mock_lb_web_service.go, internal/pkg/describe/mocks/mock_pipeline.go, internal/pkg/describe/mocks/mock_pipeline_status.go, internal/pkg/describe/mocks/mock_service.go, internal/pkg/describe/mocks/mock_status.go, internal/pkg/docker/mocks/mock_docker.go, internal/pkg/template/mocks/mock_template.go
=> fix(describe): use new deploy store API to improve Describe

README.md
=> docs: update README with preview instead of beta

README.md
Add homebrew install directions
=> docs: add homebrew install directions

site/content/en/docs/Installation/_index.md
Update the docs with homebrew instructions. 
=> docs: homebrew install directions

internal/pkg/cli/storage_init.go, site/content/en/docs/Concepts/environments.md, site/content/en/docs/Concepts/services.md, templates/environment/cf.yml
Just found some typos reading our docs. 
=> docs: misspellings

NOTICE
=> docs: update NOTICE with AWS Copilot CLI

site/content/en/docs/Concepts/services.md
=> docs: fix incorrect environment reference in docs

internal/pkg/cli/pipeline_show.go, internal/pkg/cli/pipeline_status.go
=> chore(cli): show "pipeline status" and "pipeline show" cmds

internal/pkg/term/prompt/prompt.go
=> refactor(prompt): move split fn to var for TemplateFuncs vars to share

internal/pkg/cli/app_init.go, internal/pkg/cli/app_init_test.go
=> fix(cli): app init not check domain name if flag not set

README.md
=> docs(README): update installation guide for v0.2.0

README.md
=> docs(README): include the latest release version as a badge

Makefile
Add -race flag when building and testing to catch data race issues.
=> chore(makefile): add -race when building and testing

site/README.md, site/package-lock.json, site/package.json
https://github.com/aws/copilot-cli/network/alert/site/package-lock.json/lodash/closed
=> build(site): update dependencies to mitigate CVE-2020-8203

.mergify.yml
Add condition where 2 approvals is not required when the author is dependabot.
=> chore: automerge dependabot updates

internal/pkg/cli/init.go, internal/pkg/workspace/workspace.go, internal/pkg/workspace/workspace_test.go
=> chore(cli): display warning only if not in root of Git repository

internal/pkg/aws/secretsmanager/secretsmanager.go, internal/pkg/aws/sessions/sessions.go, internal/pkg/cli/app_delete.go, internal/pkg/cli/app_delete_test.go, internal/pkg/cli/app_init.go, internal/pkg/cli/env_delete.go, internal/pkg/cli/env_init.go, internal/pkg/cli/init.go, internal/pkg/cli/pipeline_delete.go, internal/pkg/cli/pipeline_init.go, internal/pkg/cli/pipeline_show.go, internal/pkg/cli/pipeline_status.go, internal/pkg/cli/pipeline_update.go, internal/pkg/cli/svc_delete.go, internal/pkg/cli/svc_delete_test.go, internal/pkg/cli/svc_deploy.go, internal/pkg/cli/svc_init.go, internal/pkg/cli/svc_logs.go, internal/pkg/cli/svc_package.go, internal/pkg/cli/task_run.go, internal/pkg/config/store.go, internal/pkg/deploy/deploy.go, internal/pkg/describe/env.go, internal/pkg/describe/pipeline.go, internal/pkg/describe/pipeline_status.go, internal/pkg/describe/service.go, internal/pkg/describe/status.go, internal/pkg/template/template_integration_test.go
=> refactor(session): rename session pkg to sessions

e2e/Dockerfile
=> test(e2e): fix binary name in Dockerfile

internal/pkg/cli/env_init.go, internal/pkg/cli/env_init_test.go, internal/pkg/cli/flag.go, internal/pkg/cli/init.go, internal/pkg/cli/interfaces.go, internal/pkg/cli/mocks/mock_interfaces.go, internal/pkg/term/selector/creds.go
Resolves #1228 and resolves #1115 
=> feat(cli): enable using temp creds when initializing an env

e2e/internal/client/cli.go
=> test(e2e): fix broken env init e2e test due to flag name change

README.md
=> docs: update README.md to v0.3.0
