- e2e/cli_test/init/init_test.go
- e2e/cli_test/internal/creds/aws_config.go
This is the first e2e test for `archer init`.
Fixes #99.
> Add E2E tests for init

- internal/pkg/aws/session/session.go
Before the change:
```
$ env -i AWS_DEFAULT_REGION=us-west-1 ./bin/local/archer project ls
Error: NoCredentialProviders: no valid providers in chain. Deprecated.
For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```
After the change:
```
env -i AWS_DEFAULT_REGION=us-west-1 ./bin/local/archer project ls
Error: NoCredentialProviders: no valid providers in chain
caused by: EnvAccessKeyNotFound: failed to find credentials in the environment.
SharedCredsLoad: failed to load profile, .
EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get http://169.254.169.254/latest/meta-data/iam/security-credentials/: dial tcp 169.254.169.254:80: connect: host is down
```
Fixes #163.
By submitting this pull request, I confirm that you can …
> Enable verbose error message for credential issues

- Makefile
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/store/ssm/ssm_integration_test.go
- templates/environment/cf.yml
* Add integration test for spinning up environments
* These ECR repos will fail to spin up if your project/env name
have upper/lower case. This will be solved once we make our
env/project names case sensitive (if we choose not to go that route
we can store the ECR name in the env param and let CF generate it -
though then we'd miss out on the nice namespacing feature of ECR).
* Update the integration test target / ssm test names to be more clear.
Fixes #189
> Add ECR to Env CloudFormation Template

- internal/pkg/cli/env.go
- internal/pkg/cli/env_add.go
Rename the `env add` command to `env init` to be consistent with our [style guide's grammar](https://github.com/aws/amazon-ecs-cli-v2/blob/master/STYLE_GUIDE.md#command-grammar).
> Rename "env add" cmd to "env init"

- internal/pkg/cli/init.go
- internal/pkg/manifest/app_manifest.go
- internal/pkg/manifest/app_manifest_test.go
This is necessary because we need a namespace for the pipeline manifest.
Fixes #207.
> Rename manifest.Create() to CreateApp

- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
Currently, we'll only check to see if an existing manifest dir
was created in the current directory.
This leads to a bug where if someone runs init in a subdirectory
of a workspace, the manifest directory is re-created.
> Fix workspace idempotency issue

- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/init.go
- internal/pkg/cli/init_test.go
Refactor renaming `Opts` structs that are not consistent with the file names.
> Rename Opts structs to match file names

- internal/pkg/archer/env.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/init.go
- internal/pkg/cli/init_test.go
- internal/pkg/deploy/cloudformation/changeset.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/deploy/cloudformation/env.go
- internal/pkg/deploy/cloudformation/env_test.go
- internal/pkg/deploy/cloudformation/errors.go
- mocks/mock_env.go
- templates/environment/cf.yml
This PR does a couple of things:
* Creates a DeployEnvironmentInput which contains the fields
which are needed to create an environment.
* Separate the Tags/Parameter/Template/StackName generation
into a separate env.go file so cloudformation.go can focus on
deployment logic. I think this will make adding application/pipeline
deployments much easier.
* Stores the ECR URL for the environment into the env struct.
Fixes #191 
> Separate Environment deploy details from main CF file

- internal/pkg/cli/project_init.go
- internal/pkg/cli/project_init_test.go
- internal/pkg/workspace/workspace.go
This is a requirement for #109.  
Currently,  `project init` misses the additional work that we put into `init`.
> Reach parity between "archer project init" and "archer init"

- internal/pkg/archer/env.go
- internal/pkg/manifest/pipeline.go
- internal/pkg/manifest/pipeline_test.go
- templates/cicd/pipeline.yml
It consolidates the 2 environment data models into one so that we don't have 2 data models for the same type of entity: Archer Environment.
This PR fixes #231 
> Consolidate the environment data models

- cmd/archer/template/macro.go
- internal/pkg/cli/app_init.go
- internal/pkg/cli/completion.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_list.go
- internal/pkg/cli/project_init.go
- internal/pkg/cli/project_list.go
Sometimes we want the examples in the commands to **not** start with "$" (for example #229)
Start example code highlights with "/code " instead.
> Use "/code " to highlight code samples in cmd examples

- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/init.go
- internal/pkg/cli/init_test.go
- internal/pkg/cli/validate.go
- internal/pkg/store/ssm/ssm.go
- internal/pkg/store/ssm/ssm_test.go
Resolves #109
We now call `env init` from within `archer init` which removes duplicate code across two commands.
> Refactor Init to use InitEnv cmd internally

- cmd/archer/main.go
- cmd/archer/template/version.go
- internal/pkg/cli/version.go
Before:
```bash
$ ./bin/local/archer --version
Archer version: 82ad210$ ./bin/local/archer version
Archer version: 82ad210, built for local$
```
After:
```bash
$ ./bin/local/archer --version
Archer version: 7456c88
$ ./bin/local/archer version
Archer version: 7456c88, built for local
$  
```
> Add newline to version outputs

- internal/pkg/archer/env.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/env_init.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/deploy/cloudformation/env.go
- internal/pkg/deploy/cloudformation/env_test.go
- internal/pkg/deploy/deploy.go
- internal/pkg/manifest/pipeline.go
- internal/pkg/store/ssm/ssm.go
- mocks/mock_env.go
1. Moved the `DeployEnvironmentInput` struct to `deploy` pkg
2. Renamed the struct to just `Environment`
> Move DeployEnvironmentInput to the deploy pkg

- internal/pkg/manifest/app_manifest_test.go
- internal/pkg/manifest/lb_fargate_manifest.go
- internal/pkg/manifest/lb_fargate_manifest_test.go
- templates/lb-fargate-service/manifest.yml
Add a new method `EnvConf` that returns the manifest's configuration for a given environment.
Resolves #252
> Apply environment overrides to a LBFargateManifest configuration

- buildspec.yml
This PR adds a buildspec which outputs nine labeled binaries each time it is run (ie, on PR merge): latest, commit-hash-only, and version, for each operating system supported in `make release`.
Commit hash is produced by taking the first seven characters of `git rev-parse HEAD`. 
Version tag is produced by the last word of the `--version` flag. 
Latest will be continually overwritten.
Addresses our continuing need for easily accessible binaries for bug bashes and testing efforts. 
> Add buildspec to source control in master

- internal/pkg/manifest/pipeline.go
- internal/pkg/manifest/pipeline_test.go
This makes pipeline Cloudformation template rendering a little bit easier because in the template we have separate fields for the repository owner and repository name.
N/A
> Renamed the Repository field to OwnerAndRepository to be more explicit

- buildspec.yml
Replace bash parameter substitution with call to `cut` for better compatibility with standard build image.
Remove latest version generation from buildspec.
Change gen-mocks to tools for more explicit declaration of work done by Codebuild. This improves future legibility.
Addresses ongoing internal CD needs. 
> Clarify buildspec and tailor to internal CD use case.

- buildspec.yml
Error in squashing commits in #276 resulted in the accidental removal of a crucial variable used in the title of the manifest file. This caused the deployment of the binaries generated on merge of #276 to fail, as the manifest generated by build stage was titled ".manifest" and the release stage expected "$COMMIT_ID.manifest" to exist.
> Re-set accidentally removed COMMIT_ID variable in buildspec

- go.sum
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/deploy/cloudformation/errors.go
- internal/pkg/deploy/cloudformation/project.go
- internal/pkg/deploy/cloudformation/project_test.go
- internal/pkg/deploy/cloudformation/stack/errors.go
- internal/pkg/deploy/cloudformation/stack/project.go
- internal/pkg/deploy/cloudformation/stack/project_test.go
- internal/pkg/deploy/cloudformation/stack/tags.go
- templates/project/cf.yml
- templates/project/project.yml
This change adds the ability to create a StackSet
for project infrastructure.
This includes ECR Repos, KMS Keys, S3 buckets, etc.
This is the 1st pass at this (since it was getting big).
The basic flow will be:
1. Project init > Sets up 1 stack for StackSet roles,
set up a StackSet (pretty quick ~ 7 seconds)
2. When adding an environment, spins up a StackSet if
the environment is in a region no existing envs are in.
3. When adding a new application or account, update all existing
StackSet instances.
> Implement Project Resources Implementation in CF

- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/stack/project.go
- internal/pkg/deploy/cloudformation/stack/project_test.go
- templates/project/cf.yml
CloudFormation logical IDs can't have dashes in the name. This
change "sanitizes" the logical IDs we generate in the project
resources stack.
We'll replace dashes with the word DASH (since caps aren't
allowed in app/project names - we won't have any collisions with
any real apps, which may have dash in their name).
> Fix project-resources template for apps with "-" in the name

- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/validate.go
- internal/pkg/cli/validate_test.go
ECR repositories do not accept upper case characters due to Reasons™️.
This catches the error so it doesn't fail when deploying with CFN.
Fixes #185.
> Validate that archer resource names are lowercase

- internal/pkg/deploy/cloudformation/pipeline.go
- internal/pkg/deploy/cloudformation/pipeline_test.go
- internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml
- internal/pkg/deploy/deploy.go
- internal/pkg/deploy/deploy_test.go
- internal/pkg/manifest/pipeline_test.go
- templates/cicd/pipeline.yml
- templates/cicd/pipeline_cfn.yml
This PR makes it possible to render a deployable CodePipeline in the form of Cloudformation template. For now it’s not hooked up into any archer command yet but the generated template has deployed successfully.
What’s working:
1. A deployable CodePipeline with a Source stage that can fetch code from Github
2. A Build stage that only runs `ls` and outputs everything (i.e. `**/*`) as built artifacts for now.
What’s not working:
1. When attempted to deploy using Cloudformation actions, they failed with `Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied`. Need to investigate further.
Update: Turns out this is just because my artifact buckets were manually created and do not have bucket policy to allow cross-account access (from env account back to the tools …
> Implement preliminary pipeline CFN dynamic rendering

- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_init.go
* Change `app` flag in `app deploy` sub-command to `name`
* Remove `project` flag from the `init` workflow `app deploy` example 
> Make app deploy flag and examples consistent

- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_deploy_test.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/app_package_test.go
- internal/pkg/cli/cli.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/init.go
- internal/pkg/cli/pipeline_init.go
Commands should access the project name by querying the ProjectName.
If the ProjectName is empty in globalOpts, then it queries viper.
Fixes #295 
> Add a ProjectName method to globalOpts

- internal/pkg/deploy/cloudformation/app.go
- internal/pkg/deploy/cloudformation/app_test.go
* Added a `DescribeChangeSet` call when an error is returned from `WaitUntilChangeSetCreateComplete` to check if there are no changes
* Replaced `"UPDATE"` magic strings with `cloudformation.ChangeSetTypeUpdate`
#304 
> Handle no ChangeSet changes on app deploy gracefully

- internal/pkg/aws/ecr/ecr.go
- internal/pkg/aws/ecr/erc_test.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/deploy/cloudformation/project.go
- internal/pkg/deploy/cloudformation/project_test.go
- internal/pkg/deploy/cloudformation/stack/project.go
- internal/pkg/deploy/cloudformation/stack/project_test.go
- internal/pkg/deploy/cloudformation/stack/template_functions.go
This adds the ability to get project resources by
reading the output of project resource cloudformation stacks.
> Add implementation for Project Resources

- internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml
- templates/cicd/pipeline_cfn.yml
- templates/project/cf.yml
The artifact bucket and corresponding encryption key used by the CodePipeline are created via the stackset. Since CodePipeline is provisioned in a separate CF stack, we need to create a cross-stack reference.
Closes #331.
> Cross reference the KMS key in CodePipeline

- internal/pkg/deploy/cloudformation/stack/pipeline_test.go
- internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml
- templates/cicd/pipeline_cfn.yml
By removing the field "BuildSpec", CodeBuild will default to use the file named "buildspec.yml" that is checked into the source code. 
Addresses #324.
> Defaults to use the buildspec.yml

- internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml
- templates/cicd/pipeline_cfn.yml
The manual approval step was added before any application can be deployed in the production stage because the RunOrder of the approval step is the smallest compared to all apps (which all use 2).
Closes #220.
After deployment, the pipeline looks like this with an approval step that blocks all deployment to the prod stage but not the other stages:
> Added manual approval step

- .gitignore
- Makefile
- cf-custom-resources/jest.config.js
- cf-custom-resources/lib/dns-cert-validator.js
- cf-custom-resources/lib/dns-delegation.js
- cf-custom-resources/package-lock.json
- cf-custom-resources/package.json
- cf-custom-resources/test/dns-cert-validator-test.js
- cf-custom-resources/test/dns-delegation-test.js
- templates/templates.go
These custom resources allow us to do cross account dns delegation
as well as cert validation in our environment stack. 
This also updates the Makefile to run the jest tests as part of our test
target.
This also updates the Makefile to minify the custom resources
and copy them to templates/custom-resources so that they can be
packed. These minified artifacts are then deleted after they
are incorporated into packr.
The Cert custom resources is yoinked from CDK.  The DNS Delegation is home spun.
This solution is a bit of a stop gap until we can start vending these custom resources another way. Perhaps through S3 and we can just inject them into templates via an S3 URL (especially since inline resources have a limit of 4KB).
> Add custom resources for DNS Delegation and Cert Validation

- internal/pkg/deploy/cloudformation/stack/pipeline.go
- internal/pkg/deploy/cloudformation/stack/pipeline_test.go
- internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml
- templates/cicd/pipeline_cfn.yml
Enable customers to run their buildspec_integ.yml after deploying to each stage. The CodeBuild project is provided with the name of the stage that it is validating against. 
Closes #340.
> Added approval step after deploying to each stage

- cf-custom-resources/package-lock.json
- internal/pkg/archer/workspace.go
- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/app_package_test.go
- internal/pkg/cli/pipeline_init.go
- internal/pkg/cli/pipeline_init_test.go
- internal/pkg/cli/project_init.go
- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
- mocks/mock_workspace.go
These methods are generic enough so that we can write and read files that are under the "ecs-project" directory. This PR renames them.
> Rename ReadManifestFile and WriteManifestFile to Read/WriteFile

- internal/pkg/deploy/cloudformation/stack/pipeline.go
- internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml
- templates/cicd/pipeline_cfn.yml
This allows CFN to set a role name for us, which is fine since these
names are not referred to outside the template. This bypasses the need
to check that the role name satisfies the 64-character limit.
See: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html
> Remove roleName

- internal/pkg/deploy/cloudformation/testdata/rendered_pipeline_cfn_template.yml
- templates/cicd/pipeline_cfn.yml
The CodeBuild project that runs integration tests in the pipeline need at least the Cloudwatch permissions.
Closes #379.
> Added Cloudwatch permission to the integ test role

- cmd/archer/main.go
- internal/pkg/cli/completion.go
Generate a completer for the root command, not for the completion command
Fixes #119
> Fix shell completion

- internal/pkg/archer/project.go
- internal/pkg/cli/deploy.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/mocks/mock_deploy.go
- internal/pkg/cli/mocks/mock_projectservice.go
- internal/pkg/cli/project_init.go
- internal/pkg/cli/project_init_test.go
- internal/pkg/deploy/cloudformation/changeset.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/deploy/cloudformation/env.go
- internal/pkg/deploy/cloudformation/pipeline.go
- internal/pkg/deploy/cloudformation/project.go
- internal/pkg/deploy/cloudformation/project_test.go
- internal/pkg/deploy/cloudformation/stack/project.go
- internal/pkg/deploy/cloudformation/stack/project_test.go
- internal/pkg/deploy/project.go
- templates/project/project.yml
Attach environment principal to DNS Delegation Policy
This change makes it so we can do cross-account DNS delegation. It
grants the environment permission to update the project's hosted zone.
TODO: the project.yml template is not complete, it just adds a role.
But this change adds the infrastructure to add an environment to a
project's DNSDelegation role.
> DNS delegation part 1

- internal/pkg/deploy/cloudformation/app.go
- internal/pkg/deploy/cloudformation/app_test.go
- internal/pkg/deploy/cloudformation/changeset.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/deploy/cloudformation/env_test.go
- internal/pkg/deploy/cloudformation/project.go
- internal/pkg/deploy/cloudformation/project_test.go
If we pass in our own waiters, we can specify
the wait time that CF waits before checking
the status of creating stacks, updating them, etc.
This helps a lot, especially since we use changesets
and changeset creation is usually much faster than 30s.
a full project init w/ envs went from 8m 40s -> 7m 20s
> Reduce wait time for CF polling from 30s -> 3s

- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
- internal/pkg/deploy/cloudformation/errors.go
- internal/pkg/deploy/cloudformation/project_test.go
- internal/pkg/deploy/cloudformation/stack_status.go
This fixes and enhances some cf error handling:
1. For create, if a stack was failed to have been crated,
we'll delete it and then create the stack. This means
if someone creates an env stack, it fails, and the run
env init again, it'll delete the old failed stack and
try to create it again. We only do this for stacks
which failed cration.
2. For both update/create we error out if a stack is
already being updated.
This doesn't fix the bug where if a stack does already exist
we don't write it to SSM.
> Tighten up CloudFormation error handling

- internal/pkg/cli/deploy.go
- internal/pkg/cli/init.go
- internal/pkg/cli/init_test.go
- internal/pkg/cli/mocks/mock_deploy.go
Sample output:
```
→ ./bin/local/archer init
Note: It's best to run this command in the root of your workspace.
Welcome to the ECS CLI! We're going to walk you through some questions 
to help you get set up with a project on ECS. A project is a collection of 
containerized applications (or micro-services) that operate together.
Looks like you don't have any existing projects. Let's create one!
? What would you like to call your project? myproj
? Which type of infrastructure pattern best represents your application? Load Balanced Web App
? What do you want to call this Load Balanced Web App? myapp
? Which Dockerfile would you like to use for myapp app? myapp/Dockerfile
Ok great, we'll set up a Load Balanced Web App named myapp in project myproj.
✔ Success! Created the infrastructure to …
```
> Add app deploy to init

- cf-custom-resources/lib/dns-cert-validator.js
I've noticed them taking around ~4 mins to
have all its resources removed from it.
> Increase delete wait time for ACM certs

- internal/pkg/deploy/cloudformation/changeset.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/cloudformation_test.go
This change makes it so we don't fail
if there are no changes to a stack.
It also cleans up empty changesets so they
don't clutter a customer's account.
I yoinked some of the code directly from @sonofachamp :D
> Ignore empty changesets

- internal/pkg/deploy/cloudformation/pipeline.go
The PR fixes 2 issues:
1. We did not properly wait for pipeline stack creation/update
2. We could not update the pipeline stack because the stack already exists
Fixes #414. And fixes #413.
> Conditionally create or update the pipeline and wait til succeess

- internal/pkg/cli/env_init.go
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- internal/pkg/deploy/cloudformation/project_test.go
- internal/pkg/deploy/cloudformation/stack/env.go
- internal/pkg/deploy/cloudformation/stack/env_test.go
- internal/pkg/deploy/cloudformation/stack/project.go
- internal/pkg/deploy/cloudformation/stack/project_test.go
- internal/pkg/deploy/env.go
- templates/environment/cf.yml
- templates/project/project.yml
This pipes through the DNS name of the project to the env
templates, and wires in the custom resources.
TODO: Add the integration tests for this - but the
existing, non DNS integ tests are running fine.
I manually ran the env setup for a DNS project. 
> Set up resources in env/project stack for DNS Delegation

- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/app_package_test.go
- internal/pkg/deploy/cloudformation/app.go
- internal/pkg/deploy/cloudformation/app_test.go
- internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go
- internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go
- internal/pkg/deploy/cloudformation/stack/testdata/rendered_pipeline_cfn_template.yml
- templates/cicd/pipeline_cfn.yml
- templates/lb-fargate-service/cf.yml
- templates/lb-fargate-service/params.json
This change updates the lb fargate app to create an https
listner if the project is configured for https.
It also enables cross account deployments and brings
the app stack name in line with the codepipeline's apps
(project-env-app).
> Add HTTPS to lb_fargate_app template & x-account deploys

- internal/pkg/cli/init.go
- internal/pkg/cli/init_test.go
Add check against `ShouldDeploy` flag in `deployApp` function.
Sample output:
```
→ ./bin/local/archer init
Note: It's best to run this command in the root of your workspace.
Welcome to the ECS CLI! We're going to walk you through some questions 
to help you get set up with a project on ECS. A project is a collection of 
containerized applications (or micro-services) that operate together.
Looks like you don't have any existing projects. Let's create one!
? What would you like to call your project? myproj
? Which type of infrastructure pattern best represents your application? Load Balanced Web App
? What do you want to call this Load Balanced Web App? myapp
? Which Dockerfile would you like to use for myapp app? myapp/Dockerfile
Ok great, we'll set up a Load Balanced Web App named myapp …
```
> Check ShouldDeploy flag before deploying app

- internal/pkg/aws/handlers/user_agent_handler.go
- internal/pkg/aws/session/session.go
Add User-Agent to all AWS SDK calls.
Fixes: https://github.com/aws/amazon-ecs-cli-v2/issues/255
> Add user agent to all aws-sdk calls

- templates/lb-fargate-service/cf.yml
Applications that are slow to startup (> 30secs) kept failing the healthchecks. Increasing the grace period to 1min increases the odd that apps will be running by then.
> Increase HealthCheckGracePeriodSeconds to 1 min

- internal/pkg/archer/manifest.go
- internal/pkg/archer/workspace.go
- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_deploy_test.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/app_package_test.go
- internal/pkg/cli/pipeline_update.go
- internal/pkg/cli/pipeline_update_test.go
- internal/pkg/manifest/app_manifest.go
- internal/pkg/manifest/lb_fargate_manifest.go
- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
- mocks/mock_workspace.go
There are multiple places where we need a list of unserialized app manifests. Now you can finally do that :)
Resolves #452.
> Workspace can return a list of unmarshalled app manifests

- cf-custom-resources/lib/alb-rule-priority-generator.js
- cf-custom-resources/test/alb-rule-priority-generator-test.js
- internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go
- internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go
- templates/environment/cf.yml
- templates/lb-fargate-service/cf.yml
Right now, we pass in the Listener rule value of 1.
This works for 1 app, but not if we want to add another.
To solve this, we have to use a custom resource to generate
the next available rule priority by looking at the existing LB
Listener rules, and returning the max + 1.
This change also fixes a race condition with spinning up the
Listener and the ECS service (the service needs the Listener
to be created first). I had to do a little trick do to a conditional
depends on using a waiter.
This change, completely unrelated, also exposes the LB DNS path
as an env variable to the task definition we create.
> Fix Multiple Listener Rules

- internal/pkg/cli/app_deploy.go
This change lets us recover from empty stack updates.
Right now, if we generate a changeset, we suffix it
with the image tag.
If this is empty, the changeset is kept in CF.
If we make a change that doesn't affect the tag,
we'll fail to deploy.
We should clean up those failed changesets, but for now,
to get this working, changing the ID to be a UUID.
addresses #460
> Replace ChangeSet suffix with UUID

- internal/pkg/cli/app_init.go
- internal/pkg/cli/cli.go
Addresses #332 where unit tests will fail if there is an ecs-project folder with a .ecs-workspace file which contains a project name.
The unit tests were picking that value up via the cli package init func which in turn causes unit tests that rely on an empty project name to fail.
> Fix unit test failures when ecs-project folder is in context

- internal/pkg/cli/app_delete.go
Add recommended follow-up actions to app delete to prompt pipeline update. Fix #487 usability problem.
> Add recommended follow-up actions to app delete

- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_deploy_test.go
* Updated `app deploy` workflow to trim `/Dockerfile` from manifest docker image path values
* Improved error messages and added test coverage for `getAppDockerfilePath` function
Addresses #490 
> Trim /Dockerfile from manifest image path value

- internal/pkg/cli/flag.go
- internal/pkg/cli/pipeline_init.go
Remove unused validation and flags (enablecd and deploy) in pipeline init.
> Remove unused validation and flags in pipeline init

- templates/lb-fargate-service/cf.yml
Currently the TaskRole has only `PowerUserAccess`, this change restricts the permissions to:
1. Blocks IAM calls.
2. Only storage and messaging services that are prefixed with the `{project}-{env}`
3. Tagged resources
> Update TaskRole to access only ECS CLI resources

- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/flag.go
Fix #533. I think it would be confusing if we allow "-d" flag to accept either "path to the directory that containers Dockerfile" or "path to Dockerfile". Make more sense to allow only "path to Dockerfile" using "-d" flag.
> Change -d validation to check Dockerfile for "app init"

- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
Currently `app init` will fail because it validates if the dockerfile path is a directory (need to be a file path) and the dockerfile path gets trimmed "/Dockerfile". Now remove the trim and also remove the validation for if dockerfile path is a dir or not. Just validate if the file/dir exists.
> Quick fix to app init

- internal/pkg/cli/pipeline_init.go
- internal/pkg/deploy/cloudformation/stack/project.go
html/template escapes content - which is generally not what
we want.
This was generating invalid buildspecs.
> Move to text/template instead of html/template

- STYLE_GUIDE.md
- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/project_init.go
- internal/pkg/term/color/color.go
- internal/pkg/term/prompt/prompt.go
1. The prompt now starts with a new line character.
The use of extra space makes the CLI feels less cluttered.
2. Added color.Emphasize() as a way for us to highlight
the important words in a prompt.
3. Reduced the number of colors used to only Cyan and HiCyan.
Cyan is used for user inputs, and HiCyan for outputs generated by us.
Just like spacing, this makes the CLI feel less jarring.
4. The help text is now inverted and catches the eye of the user
immediately.
> style: update prompt templates and resource colors

- internal/pkg/aws/session/session.go
- internal/pkg/cli/app_delete.go
- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/cli.go
- internal/pkg/cli/env_delete.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/init.go
- internal/pkg/cli/pipeline_update.go
- internal/pkg/cli/project_init.go
- internal/pkg/describe/describe.go
- internal/pkg/describe/webapp.go
- internal/pkg/store/secretsmanager/secretsmanager.go
- internal/pkg/store/store.go
Using [factory methods](https://refactoring.com/catalog/replaceConstructorWithFactoryFunction.html) over functions for initializing sessions allows us to mock session creation!
> refactor: replace session creation from functions to factory methods

- internal/pkg/cli/app_delete.go
- internal/pkg/cli/app_delete_test.go
The `app delete` command didn't use the `Validate`, `Ask`, and `Execute` pattern. 
This meant that it would be difficult to chain this command with another one and followed a different convention. 
> Make delete app conform to Validate, Ask, Execute

- internal/pkg/aws/session/session.go
- internal/pkg/cli/app_delete.go
- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/env_delete.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/init.go
- internal/pkg/cli/pipeline_update.go
- internal/pkg/cli/project_init.go
- internal/pkg/describe/webapp.go
- internal/pkg/store/secretsmanager/secretsmanager.go
- internal/pkg/store/store.go
Commands such as `init` can share the same `session.Provider` without having to re-create the sessions.
> refactor: use sessions as singletons

- STYLE_GUIDE.md
Update style guide to reflect how `ls` and `show` commands should be formatted (based on our discussions for app show and project ls).
> Update style guide with guidence on list and show commands

- internal/pkg/cli/cli.go
- internal/pkg/cli/env_delete.go
- internal/pkg/cli/env_delete_test.go
1. feat(env delete): prompts to select an env name instead of inputting it
2. refactor(env delete): conform to Validate -> Ask -> Execute pattern
> feat(env delete): ask user to select environment instead of writing it

- internal/pkg/archer/secret.go
- internal/pkg/aws/secretsmanager/mocks/mock_secretsmanager.go
- internal/pkg/aws/secretsmanager/secretsmanager.go
- internal/pkg/aws/secretsmanager/secretsmanager_test.go
- internal/pkg/cli/deploy.go
- internal/pkg/cli/flag.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_deploy.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/pipeline.go
- internal/pkg/cli/pipeline_delete.go
- internal/pkg/cli/pipeline_delete_test.go
- internal/pkg/cli/pipeline_init.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/pipeline.go
- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
- mocks/mock_secret.go
> feat: add "pipeline delete" command

- Makefile
- e2e/Dockerfile
- e2e/e2e.sh
- e2e/internal/client/cli.go
This is just a little clean up, but removes the interactive
flag from ducker run (causing CodeBuild to fail) and also
getting rid of the unneeded multi-stage build.
> chore(e2e): remove interactive flag form e2e command

- internal/pkg/aws/profile/profile.go
c.f.Sections returns the section names. If the profile name contains the word 'profile', it will be replaced by an empty string. 
Example:
```
profile profile1
```
becomes
```
1
```
The change is to use ``strings.TrimPrefix`` instead.
```
profile profile1
```
becomes
```
profile1
```
Fixes #627
> fix: profile selection trims the word "profile" from profile names

- internal/pkg/aws/profile/profile.go
- internal/pkg/aws/profile/profile_test.go
The "profile" package has no unit tests, this fixes that :)
> test(profile): add unit tests to the "aws/profile" package

- e2e/init/init_test.go
- e2e/multi-app-project/multi_app_project_test.go
- e2e/multi-env-project/multi_env_test.go
CloudWatch logs can sometimes have a few second delay getting
logs from the ECS service into CloudWatch. This change makes
it so we'll wait up to 60 seconds for the logs to get there,
then we'll fail.
> test(e2e): allow for CloudWatch logs delay

- internal/pkg/addons/addons.go
- internal/pkg/addons/addons_test.go
- internal/pkg/addons/mocks/mock_addons.go
- internal/pkg/archer/app.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/app_package_test.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/workspace/errors.go
- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
Resolves #648. Also skip selecting if there's only one available app or env. By default addons template won't show up in `stdout` unless users pass in `--output-dir` flag.
> feat(cli): update app package to write nested stack template

- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_package.go
#678 didn't update the `app deploy` which calls the `Execute()` of `app package` as well. Our e2e test caught the error, which should be caught by the unit test if exists :(
> fix(cli): init addons service in app deploy

- internal/pkg/cli/app_delete.go
- internal/pkg/cli/app_delete_test.go
Currently ``ecs-preview app delete`` deletes the application entirely from all environment. These changes provide an optional flag ``--env`` that enable users to delete application from specific environment.
Addresses #589 
> feat(cli): add an optional env flag to app delete

- Makefile
- internal/pkg/deploy/cloudformation/cloudformation_integration_test.go
- templates/environment/cf.yml
- templates/lb-fargate-service/cf.yml
Related #599 
BREAKING CHANGE: Previously, the security group was defined in the application stack which meant that containers could not communicate inter-application. This change moves the security group to the environment level.
> fix!: move containers security group from app to env stack

- Makefile
- templates/lb-fargate-service/cf.yml
Resolves #647
We do not yet incorporate the `Output` values into the TaskRole or as environment variables. That'll be handled in a follow-up PR!
> feat: web app template supports nested addons stack

- e2e/multi-env-project/multi_env_test.go
There seems to be times when we call the endpoint, but
it's not quite ready yet, after we do a deployment. I can't
reproduce this localy, which leads me to believe it's because
CodeBuild instance is just faster.
This change lets the tests retry a few times (up to 10s) before
failing.
> test(e2e): add some buffer for validating endpoints

- go.sum
- templates/cicd/buildspec.yml
After #657, the structure for `ecs-project` changed. We need to update the `buildspec.yml` for pipeline as well. Otherwise the codebuild fails.
> fix(pipeline): buildspec fails to get app name to generate CFN template

- internal/pkg/aws/s3/mocks/mock_s3.go
- internal/pkg/aws/s3/s3.go
- internal/pkg/aws/s3/s3_test.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/project_delete.go
- internal/pkg/cli/project_delete_test.go
fix #700, with minor refactoring.
> fix(cli): project delete empty s3 buckets before deleting

- CONTRIBUTING.md
- internal/pkg/store/env.go
- internal/pkg/store/env_test.go
- internal/pkg/store/store_integration_test.go
when listing environments, put nonprod environments first so user keep typing "Enter" will not accidentally deploy to production.
fixes #716 
> chore: put nonprod environments before prod when listing

- internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go
- internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go
- internal/pkg/manifest/lb_fargate_manifest.go
- internal/pkg/manifest/lb_fargate_manifest_test.go
- templates/lb-fargate-service/cf.yml
- templates/lb-fargate-service/manifest.yml
- templates/lb-fargate-service/params.json
> feat: add healthcheck path to app manifest

- e2e/init/init_test.go
- e2e/multi-app-project/multi_app_project_test.go
- e2e/multi-env-project/multi_env_test.go
ALBs somtimes take more than 10 seconds to consistently
resolve a new route. This change should make our tests
more stable by giving them up to 30s to resolve.
> feat(e2e): update max retry time for http get

- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/store/app.go
- internal/pkg/store/app_test.go
- internal/pkg/store/errors.go
- internal/pkg/store/errors_test.go
- internal/pkg/store/store_integration_test.go
- internal/pkg/workspace/errors.go
- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
fix #552.
Suppose we already have created an application named "my-app". Then I run the following command again:
```
$ archer app init
Note: It's best to run this command in the root of your workspace.
? Which type of infrastructure pattern best represents your application? Load Balanced Web App
? What do you want to name this Load Balanced Web App? my-app
? Which Dockerfile would you like to use for my-app? ./Dockerfile
? What port do you want requests from your load balancer forwarded to? 80
✔ Skip writing since the manifest for my-app app already exists at ecs-project/my-app/manifest.yml
Your manifest contains configurations like your container size and ports.
✔ Created ECR repositories for application my-app.
Recommended follow-up actions:
- Update your manifest …
```
> fix(cli): make app init idempotent

- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/project_init.go
- internal/pkg/cli/project_init_test.go
- internal/pkg/deploy/cloudformation/env.go
- internal/pkg/store/env.go
- internal/pkg/store/env_test.go
- internal/pkg/store/errors.go
- internal/pkg/store/errors_test.go
- internal/pkg/store/project.go
- internal/pkg/store/project_test.go
- internal/pkg/store/store_integration_test.go
Fix #301, partially addressing #660.
> fix(cli): make env init idempotent

- internal/pkg/aws/ecs/ecs.go
- internal/pkg/aws/ecs/ecs_test.go
- internal/pkg/aws/ecs/mocks/mock_ecs.go
Add Service and Task struct to `ecs` package, so that we can get the info for ECS service and its running tasks. This PR also fixes #751 and #752.
Note that unit tests will be added later.
> feat(ecs): add Service and Task struct

- internal/pkg/cli/app_show.go
- internal/pkg/cli/project_show.go
For consistency, we changed the flags `--project` and `-p`, as well as `--app` and `-a` in project_show and app_show, respectively, to `--name` and `-n` (PR # 773). Here, I changed the flag in the example command of the help menu to reflect this change.
> fix: name flags in example of help menu

- internal/pkg/cli/pipeline.go
- internal/pkg/cli/pipeline_show.go
Basic scaffold for the `pipeline show` command. Displays help menu.
Partially addresses https://github.com/aws/amazon-ecs-cli-v2/issues/799
> feat: scaffold for pipeline show

- internal/pkg/cli/app_init.go
The example was spaced with a tab character instead of two spaces and it looked awkward.
> chore: fix spacing for app init example

- internal/pkg/aws/ecs/ecs.go
- internal/pkg/aws/ecs/ecs_test.go
Quick fix the bug that app-status panics when task status "startedAt" is nil. Thanks @kohidave for finding the bug!
When running `app status` at the app deployment stage, golang panics:
```
[ecs-kudos-api] ecs-v2 app status                                                                                                                                                                          master  ✭
Only found one deployed app, defaulting to: api (test)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1abf342]
goroutine 1 [running]:
github.com/aws/amazon-ecs-cli-v2/internal/pkg/aws/ecs.(*Task).TaskStatus(0xc000030f20, 0xc0000f222e, 0x22, 0xc0000f2251) …
```
> fix(cli): fix the bug for panic when startedAt is nil

- e2e/multi-app-project/multi_app_project_test.go
Removed the provided port from the end to end test frontend app init params to force copilot to extract the port from the EXPOSE statement in the e2e frontend dockerfile. 
Related to #747
> chore(e2e): Force e2e test to extract port from frontend dockerfile

- internal/pkg/deploy/cloudformation/stack/lb_fargate_app.go
- internal/pkg/deploy/cloudformation/stack/lb_fargate_app_test.go
- internal/pkg/template/mocks/mock_template.go
- internal/pkg/template/template.go
- internal/pkg/template/template_test.go
- templates/applications/common/cf/addons.yml
- templates/applications/common/cf/envvars.yml
- templates/applications/common/cf/executionrole.yml
- templates/applications/common/cf/loggroup.yml
- templates/applications/common/cf/service-base-properties.yml
- templates/applications/common/cf/taskrole.yml
- templates/applications/lb-web-app/cf.yml
Part 1 of #833
The files under `templates/applications/common/cf/` are sections that should be shared across all app types. This will allow us to DRY our templates. We should be able to write new app type templates faster, remove the chance of errors while copy pasting, and keep things consistent across applications.
Please let me know if you have any disagreements, also if you think there are other sections that can be extracted to the `common/cf` dir.
> chore: extract common sections across app types into separate dir

- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/pipeline_delete.go
- internal/pkg/cli/pipeline_delete_test.go
- internal/pkg/cli/project_delete.go
- internal/pkg/cli/project_delete_test.go
- internal/pkg/workspace/errors.go
- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
Previously, project delete would fail if there was no pipeline.yml file in the workspace directory. However, it is possible that the project does not have a pipeline manifest at all and this should not cause project delete to fail. This change fixes that bug.
> fix: do not fail project delete if pipeline manifest does not exist

- e2e/internal/client/cli.go
AppPort is not a required field if we can parse it from the Dockerfile.
This change removes the flag if it's not provided explicitly.
Otherwise the --port value is set to the empty string "" and the CLI blows up.
> test: fix e2e by applying optional flags only if they're provided

- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_deploy_test.go
- internal/pkg/deploy/cloudformation/app.go
- internal/pkg/deploy/cloudformation/app_test.go
- internal/pkg/deploy/cloudformation/cloudformation.go
- internal/pkg/deploy/cloudformation/stack/app.go
All application stacks need to implement the cloudformation.StackConfiguration
interface. By having "DeployApp" accept that interface we can have the
method deploy any type of application.
> refactor: DeployApp accepts an interface instead of cfn primitives

- internal/pkg/deploy/cloudformation/stack/pipeline.go
- internal/pkg/deploy/cloudformation/stack/pipeline_test.go
This was creating inconsistencies between the name of the stack in the
pipeline.yml file and the one being deployed
> fix: remove project prefix when creating pipeline stack name

- internal/pkg/cli/pipeline_delete.go
- internal/pkg/cli/pipeline_delete_test.go
Due to 62e5515b, we no longer need to append the ProjectName to the
pipeline name to find the name of the stack.
> fix: delete correct pipeline stack

- internal/pkg/aws/cloudwatch/cloudwatch.go
- internal/pkg/aws/cloudwatch/cloudwatch_test.go
- internal/pkg/aws/cloudwatch/mocks/mock_cloudwatch.go
Follow-up to https://github.com/aws/amazon-ecs-cli-v2/pull/865
> refactor: rename cloudwatch pkg internal interface

- internal/pkg/aws/codepipeline/codepipeline.go
- internal/pkg/aws/codepipeline/codepipeline_test.go
- internal/pkg/aws/codepipeline/mocks/mock_codepipeline.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/pipeline_show.go
- internal/pkg/cli/pipeline_show_test.go
Previously, using the codepipeline#ListPipelines API would return all
pipelines in a user's account. This change uses ResourcesGroups to
filter pipelines by tags, so as to only return pipelines associated with
a given project (soon to be called application).
> refactor: use ResourceGroups to retrieve pipelines

- internal/pkg/cli/app_show.go
- internal/pkg/cli/app_show_test.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/describe/backend_app.go
- internal/pkg/describe/backend_app_test.go
- internal/pkg/describe/lb_web_app.go
- internal/pkg/describe/lb_web_app_test.go
- internal/pkg/describe/mocks/mock_lb_web_app.go
With this change `app show` now should be able to show running backend applications. However, we cannot test this feature manually until `app deploy` supports deploying backend app.
Ideally the output for app show for backend app should be:
```
About
Project           my-project
Name              my-app
Type              Backend App
Configurations
Environment       Tasks               CPU (vCPU)          Memory (MiB)        Port
test              1                   0.25                512                 5000
prod              2                   0.5                 1024                5000
Service Discovery:
test,prod         my-app.my-project.local:5000
Variables
Name              Environment         Value
```
By submitting this pull request, I confirm that you can use, modify, copy, …
> feat(cli): add app show support for backend app

- internal/pkg/aws/cloudformation/changeset.go
- internal/pkg/cli/app_deploy.go
- templates/applications/backend-app/cf.yml
Once we merge https://github.com/aws/amazon-ecs-cli-v2/pull/876, it should be a single line update to add the constructor for a BackendAppDescriber.
> chore(cli): app deploy can get the uri of multiple app types

- e2e/init/init_test.go
- e2e/internal/client/outputs.go
After #876 we start showing service discovery endpoint for `app show`. So we need to add e2e test for it as well.
> chore(e2e): add e2e test for app show for service discovery

- internal/pkg/cli/app_delete.go
- internal/pkg/cli/app_delete_test.go
- internal/pkg/cli/app_deploy.go
- internal/pkg/cli/app_deploy_test.go
- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/app_list.go
- internal/pkg/cli/app_list_test.go
- internal/pkg/cli/app_package.go
- internal/pkg/cli/app_package_test.go
- internal/pkg/cli/app_show.go
- internal/pkg/cli/app_show_test.go
- internal/pkg/cli/cli.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/pipeline_update.go
- internal/pkg/cli/pipeline_update_test.go
- internal/pkg/cli/project_init.go
- internal/pkg/cli/project_init_test.go
- internal/pkg/workspace/errors.go
- internal/pkg/workspace/workspace.go
- internal/pkg/workspace/workspace_test.go
BREAKING CHANGE: The following user-visible changes are introduced:
1. The `ecs-project` directory is renamed to `copilot`.
2. The `.ecs-workspace` summary file is renamed to `.workspace`.
3. Errors include the term "service" and "application".
> chore(workspace)!: use Application, Service, and Copilot terms

- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/selector.go
- internal/pkg/cli/selector_test.go
Selector is a centralized struct that holds the logic
for asking a user to select an app, service, and env.
It uses all the new config* structs, except for services,
since the servicelister returns apps.
Resolves #842 
> chore: add selector struct

- internal/pkg/cli/env_init.go
Tiny fix to env init. 
When I went to create an env in a project with DNS, I got a segfault. Turns out that we were checking the project for DNS requirements before we initialized any of the sessions via the call to initProfileClients().
No tests added because this wasn't caught by mock tests. 
> fix(env): initialize profile sessions before checking for dns delegation

- templates/cicd/buildspec.yml
> fix(pipeline): buildspec works with dockerfiles in subdirs

- internal/pkg/cli/app_status_test.go
- internal/pkg/describe/status.go
- internal/pkg/describe/status_test.go
The `humanize.Time` function outputs time in human friendly ways
(ex: "1 day ago"). Our test cases were expecting the string "1 month ago",
but a few hours ago the output from `humanize.Time` changed to "2 months ago" so the tests in master started failing.
This change hard-codes `time.Now` for the test, so that humanize.Time
always returns the same value.
We also moved the test from "cli/app_status_test.go" to "describe/status_test.go".
*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*
> test(describe): fix flaky "app status" tests due to passing time

- internal/pkg/cli/env_delete.go
- internal/pkg/cli/env_delete_test.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/env_list.go
- internal/pkg/cli/env_list_test.go
- internal/pkg/cli/env_show.go
- internal/pkg/cli/env_show_test.go
- internal/pkg/cli/init.go
- internal/pkg/term/color/color.go
Copilot renaming for env subcommands including
- `env delete`
- `env init`
- `env list`
- `env show`
> chore(cli): copilot renaming for env subcommands

- internal/pkg/cli/app_show_test.go
- internal/pkg/cli/env_show_test.go
- internal/pkg/cli/svc_list_test.go
- internal/pkg/config/service.go
The field starts with a capital letter right now, which is unlike any other fields in our configurations.
> chore: rename JSON field to "app" from "App" for a service

- cmd/copilot/main.go
- internal/pkg/cli/env.go
- internal/pkg/cli/wiki.go
> chore: fix env command message and rename "wiki" to "docs" cmd

- cmd/copilot/description.go
The same constant is defined in `description_windows.go` which results in the error when building the windows binary:
```
cmd/copilot/description_windows.go:7:2: shortDescription redeclared in this block
previous declaration at cmd/copilot/description.go:7:21
make: *** [compile-windows] Error 2
```
By adding a build tag to `description.go` saying that it should be used for all platforms except windows, the cli builds.
> fix: add build tag to description.go to make it work on windows

- templates/cicd/buildspec.yml
Since the name of the copied binary is "copilot" and the name of the directory where we put our manifest files is also "copilot", running "./copilot" would result in trying to execute the directory and the build stage failed.
This change updates the copied binary name to "copilot-linux" to avoid the confusion.
> fix: cicd buildspec works with copilot binary

- internal/pkg/template/service.go
- internal/pkg/template/service_test.go
This fix addresses an issue where sometimes secrets is nil and
sometimes it is an empty map. When there are overrides present,
secrets is not nil. This change checks to see if the *length* of
secrets is not 0.
Fixes #963
> fix: has secrets was returning true when there were 0 secrets

- go.mod
- internal/pkg/cli/svc_init_test.go
- internal/pkg/deploy/cloudformation/stack/backend_svc.go
- internal/pkg/deploy/cloudformation/stack/backend_svc_test.go
- internal/pkg/deploy/cloudformation/stack/lb_web_svc.go
- internal/pkg/deploy/cloudformation/stack/lb_web_svc_test.go
- internal/pkg/deploy/cloudformation/stack/svc.go
- internal/pkg/manifest/backend_svc.go
- internal/pkg/manifest/backend_svc_test.go
- internal/pkg/manifest/lb_web_svc.go
- internal/pkg/manifest/lb_web_svc_test.go
- internal/pkg/manifest/svc.go
- internal/pkg/manifest/svc_test.go
This PR fixes #966 and all (hopefully) related issues concerning our manifest default value and override issues by
1. substitute all fields to pointer value in light of CloudFormation template. After this change all empty value (empty string, 0, false etc.) will be considered as valid value instead of `nil` value;
2. use [mergo](https://github.com/imdario/mergo) package for environment override and remove repetitive and error-prone `copyAndApply` and `deepcopy` methods.
> fix(manifest): BackendService port and healthcheck override issue

- internal/pkg/cli/app_init.go
- internal/pkg/cli/app_init_test.go
- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/init.go
- internal/pkg/cli/init_test.go
- internal/pkg/cli/mocks/mock_prompter.go
- internal/pkg/cli/prompter.go
- internal/pkg/cli/selector/selector.go
- internal/pkg/cli/svc_deploy.go
- internal/pkg/cli/svc_init.go
- internal/pkg/cli/svc_init_test.go
- internal/pkg/term/color/color.go
- internal/pkg/term/prompt/prompt.go
- internal/pkg/term/prompt/prompt_test.go
1. We introduce a new WithFinalMessage() option in the "prompt" package to
collapse our long prompt messages to a short final message once the user
answers the prompt.
2. Prompts are now indented to signal that we're asking a user
question.
3. Combined a lot of our logs as they made it hard to read what was
actually created.
4. Changed our colorscheme to be monochrome except when we create a
resource or print code.
> style: reduce feedback noise for logs and prompts

- internal/pkg/deploy/cloudformation/stack/backend_svc.go
- internal/pkg/deploy/cloudformation/stack/backend_svc_test.go
- internal/pkg/manifest/backend_svc.go
- internal/pkg/manifest/backend_svc_test.go
- internal/pkg/manifest/lb_web_svc.go
- internal/pkg/manifest/lb_web_svc_test.go
- internal/pkg/manifest/svc.go
- internal/pkg/manifest/svc_test.go
Simplify `BackendService` and `LoadbalancedWebService` by removing fields that are duplicated with the corresponding config struct. Addressing feedback https://github.com/aws/amazon-ecs-cli-v2/pull/970#pullrequestreview-419569244
> chore(manifest): simplify load balanced/backend service struct

- internal/pkg/cli/app_init.go
> style(cli): collapse log message after user selects new app name

- internal/pkg/cli/svc_deploy.go
- internal/pkg/cli/svc_deploy_test.go
- internal/pkg/docker/docker.go
- internal/pkg/docker/docker_test.go
> fix(docker): docker build failed when multiple Dockerfile in one dir

- templates/addons/ddb/cf.yml
- templates/addons/ddb/outputs.yml
- templates/addons/ddb/policy.yml
This PR adds the cloudformation template necessary to create DDB tables on behalf of customers in storage init. 
Addresses #769 
> feat(storage): Add dynamoDB Cloudformation templates

- e2e/addons/hello/addons/params.yml
- internal/pkg/docker/docker.go
- internal/pkg/docker/docker_test.go
With #980, we fixed an issue which occurred when there were multiple dockerfiles present in the build directory. 
However, this may have broken our end to end tests, because the call to Docker was formatted as the following:
```sh
docker build -t <imageTag> path/to -f Dockerfile
```
This should be fine, but the end to end tests began to fail on Monday with the following output:
```bash
addons flow when deploying svc
svc deploy should succeed
/github.com/aws/amazon-ecs-cli-v2/e2e/addons/addons_test.go:145
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /github.com/aws/amazon-ecs-cli-v2/e2e/addons/Dockerfile: no such file or directory
Error: build Dockerfile at ./hello/Dockerfile with tag gallopinggurdey: building image: exit status 1
```
This indicates that …
> fix(docker): Fix failing end to end tests

- e2e/addons/addons_test.go
- e2e/init/init_test.go
- e2e/internal/client/outputs.go
- e2e/multi-env-app/multi_env_test.go
- e2e/multi-svc-app/multi_svc_app_test.go
- e2e/multi-svc-app/www/main.go
- internal/pkg/aws/cloudwatchlogs/cloudwatchlogs.go
- internal/pkg/aws/cloudwatchlogs/cloudwatchlogs_test.go
- internal/pkg/aws/cloudwatchlogs/event.go
- internal/pkg/cli/svc_logs_test.go
- internal/pkg/deploy/cloudformation/stack/backend_svc.go
- internal/pkg/deploy/cloudformation/stack/backend_svc_test.go
- internal/pkg/deploy/cloudformation/stack/lb_web_svc.go
- internal/pkg/manifest/backend_svc.go
- internal/pkg/manifest/backend_svc_test.go
- internal/pkg/manifest/lb_web_svc.go
- internal/pkg/manifest/lb_web_svc_test.go
- internal/pkg/manifest/svc.go
- internal/pkg/manifest/svc_test.go
- internal/pkg/template/service.go
- internal/pkg/template/service_test.go
- internal/pkg/template/template.go
- templates/services/backend/cf.yml
- templates/services/common/cf/logconfig.yml
- templates/services/common/cf/sidecars.yml
- templates/services/lb-web/cf.yml
Partially address https://github.com/aws/amazon-ecs-cli-v2/issues/875. With this PR now we can deploy a Copilot service with Firelens as the log driver to deliver logs of the main container to destinations.
Users can config Firelens in two ways:
1. Set up configurations in the manifest (unable to sent to multiple destinations though).
2. Configure using fluentbit config file. Note that this requires users to build their own custom fluentbit image and specifying their config file path.
Additionally users might need to add permissions to task role if necessary. And they are able to add their own permissions by using Copilot addons feature. Any addons policy will be added to the task role.
This PR also adjusts `svc logs` to accommodate Firelens changes.
By submitting this pull request, I …
> feat(stack): add Firelens sidecar deployment support

- internal/pkg/cli/mocks/mock_prompter.go
- internal/pkg/cli/prompter.go
- internal/pkg/term/prompt/prompt.go
- internal/pkg/term/prompt/prompt_test.go
Adds a multiselect based on survey.MultiSelect to the list of prompter methods. This will be used when selecting which attributes to use for extra LSI sort keys on a DDB table. 
> feat(prompt): Add multiselect prompter option 

- internal/pkg/addons/cloudformation.go
- internal/pkg/addons/testdata/merge/first.yaml
- internal/pkg/addons/testdata/merge/second.yaml
- internal/pkg/addons/testdata/merge/wanted.yaml
Transform can be either a single element, or a list.
If any addon contains a Transform section, we make the merged template's
Transform field a list by default and start adding all the unique
macros.
> chore(addons): merge cfn templates Transform section

- internal/pkg/cli/svc_show.go
Quick fix to get rid of the unexpected period at the end of the log output when there's no service found in the app.
> fix(cli): fix svc show log output when no svc found

- templates/cicd/pipeline_cfn.yml
Follow-up fix for https://github.com/aws/amazon-ecs-cli-v2/pull/1033/files#r443169646.
Puts the TestCommands build _after_ the deployment so that in addition to tests commands like 'make test' and 'echo', users may ping a newly-created url to confirm all is in working order.
> fix(cfn): reorder actions so BuildTestcommands follows CreateOrUpdate

- templates/cicd/pipeline_cfn.yml
Added app name to the build project name so that pipelines within the same account don't end up with the same test command build project name.
Follow-up to https://github.com/aws/amazon-ecs-cli-v2/pull/1033.
> fix(cfn): change build project name for uniqueness 

- templates/environment/cf.yml
The FARGATE and FARGATE_SPOT capacity providers are already
created and available to all accounts in Regions supported by AWS
Fargate. With this change we associate these cap providers with the
cluster, this way we can start running tasks on FARGATE_SPOT.
> feat(env): associate FARGATE and FARGATE_SPOT cap providers with cluster

- cmd/copilot/template/template.go
This command removes the orphaned "Addons" group from the `copilot -h` help menu. 
> chore(copilot): Remove separate 'addons' group from help menu

- internal/pkg/template/template_integration_test.go
- templates/services/common/cf/taskrole.yml
Previously, if an addon template did not output the ARN of a IAM ManagedPolicy, then the service template would not render with a `ValidationError: [/Resources/TaskRole/Type/ManagedPolicyArns] 'null' values are not allowed in templates`.
Fixes #1073
> fix(templates): render service cfn templates when addons have no outputs

- internal/pkg/docker/dockerfile/dockerfile.go
- internal/pkg/docker/dockerfile/dockerfile_test.go
> fix: returns the healthcheck command in an array of string

- internal/pkg/aws/cloudwatch/cloudwatch.go
- internal/pkg/aws/cloudwatch/cloudwatch_test.go
- internal/pkg/aws/cloudwatch/mocks/mock_cloudwatch.go
- internal/pkg/aws/codepipeline/codepipeline.go
- internal/pkg/aws/codepipeline/codepipeline_test.go
- internal/pkg/aws/codepipeline/mocks/mock_codepipeline.go
- internal/pkg/aws/resourcegroups/mocks/mock_resourcegroups.go
- internal/pkg/aws/resourcegroups/resourcegroups.go
- internal/pkg/aws/resourcegroups/resourcegroups_test.go
- internal/pkg/deploy/deploy.go
- internal/pkg/deploy/deploy_test.go
- internal/pkg/deploy/mocks/mock_deploy.go
- internal/pkg/describe/env.go
- internal/pkg/describe/env_test.go
- internal/pkg/describe/mocks/mock_env.go
Use resourcegroupstaggingapi instead of use resourcegroups api for `GetResourcesByTags` method. After this change `GetResourcesByTags` will also return all tags for the found resources.
> refactor(resourcegroups): use resourcegroupstaggingapi

- CHARTER.md
- internal/pkg/deploy/cloudformation/stack/name.go
- internal/pkg/deploy/cloudformation/stack/task.go
- internal/pkg/deploy/cloudformation/stack/task_test.go
- internal/pkg/deploy/deploy.go
- internal/pkg/deploy/task.go
- templates/task/cf.yml
This PR adds a CloudFormation template for a task stack, and implement stack configuration methods for task.
Related #702 
> chore(stack): add task to deploy/cfn/stack package and add template for task

- internal/pkg/cli/pipeline_init.go
- internal/pkg/cli/pipeline_init_test.go
When calling `copilot pipeline init`, if Copilot cannot parse the GitHub repo from the provided URL an error message is thrown. There is a reference to a CLI flag, `--url`, which seems to be incorrect. The correct flag is `--github-url`. This PR changes it.
> fix: Display correct GitHub URL flag name for 'copilot pipeline init' command

- internal/pkg/cli/svc_deploy.go
- internal/pkg/cli/svc_show.go
- internal/pkg/cli/svc_show_test.go
- internal/pkg/cli/svc_status.go
- internal/pkg/describe/backend_service.go
- internal/pkg/describe/backend_service_test.go
- internal/pkg/describe/lb_web_service.go
- internal/pkg/describe/lb_web_service_test.go
- internal/pkg/describe/mocks/mock_lb_web_service.go
- internal/pkg/describe/mocks/mock_service.go
- internal/pkg/describe/mocks/mock_status.go
- internal/pkg/describe/service.go
- internal/pkg/describe/status.go
- internal/pkg/describe/status_test.go
This PR focuses on
1. Avoid creating member objs repetitively in `describe` pkg when calling `NewXyzDescriber` functions.
2. Add cache to `WebAppDescriber` so that we won't call `Param()` twice for each env.
3. Remove `ServiceStatus` struct's dependency on `ServiceDescriber`.
> refactor(describe): reduce repetitive init and method calls

- templates/addons/s3/cf.yml
This PR adds a bucket policy to the CF generated by `storage init`. It now requires SSL connections in order to perform any action on a bucket. 
Related #769 
> fix(storage): add bucket policy to force SSL connections

- internal/pkg/cli/svc_delete.go
- internal/pkg/cli/svc_delete_test.go
Right now, when a customer runs `copilot svc delete --env e` copilot will delete the svc from the entire application, including the ECR repo and the SSM parameter.
The expected behavior is for copilot to only remove the service from the environment `e` - but for the service to still exist within the app. 
This change updates the service_delete code to skip removing the service from the application when the service is only being removed from one environment. 
This change might result in the service's app resources (ECR Repo, S3 Bucket, and KMS key) lingering around even if the service isn't deployed to any environment. Customers can always run `copilot svc delete` to clean up those resources. I'm hesitant to add any smarts into deleting those resources (like reference counting them) - just …
> fix: do not remove svc from app when running `svc delete --env`

- internal/pkg/aws/ec2/ec2.go
- internal/pkg/aws/ecs/ecs.go
- internal/pkg/aws/ecs/ecs_test.go
- internal/pkg/aws/ecs/errors.go
- internal/pkg/aws/ecs/mocks/mock_ecs.go
This PR includes the following changes to aws package:
1. adds a ec2 package to get subnet and security groups
2. add runtask and defaultCluster method to ecs package
Related #702 
> chore(aws): update ecs and ec2 packages to support task run command

- internal/pkg/term/prompt/prompt.go
Survey v2.0.8 introduced a breaking change where they replaced the
`core.TemplateFunc` global variable with two variables:
`core.TemplateFuncsWithColor` and `core.TemplateFuncsNoColor`.
The variable `core.TemplateFuncsNoColor` is now always used while parsing the
prompt templates. Therefore, we need to add the "split" fn to both template
funcs.
> chore(prompt): add "split" fn to TemplateFuncsNoColor var

- cmd/copilot/main.go
- cmd/copilot/template/template.go
- internal/pkg/cli/storage_init.go
This command enables the `copilot storage init` command, adds the `Addons` group to the help menu, and builds the `storage` and `storage init` commands. 
> feat(cli): enable 'storage init' command

- CHARTER.md
1. Re-order the tenets so that we start from "svc architecture patterns" ➡ "wiring services in an app" ➡ "creating a cd pipeline" ➡ "operating your services".
2. Update the "Create modern applications by default." tenet definition.
> docs(CHARTER): update tenet to mention we wire services in an app

- internal/pkg/task/config_runner_test.go
- internal/pkg/task/default_runner.go
- internal/pkg/task/default_runner_test.go
- internal/pkg/task/mocks/mock_task.go
- internal/pkg/task/task.go
1. `task` package has references to some methods whose names are updated in #1146. This PR updates `task` package to reflect those name changes.
2. re-mock interfaces in `task` package
> chore: update task package to reflect aws/ec2 method name changes 

- internal/pkg/cli/svc_package.go
We were missing an else bracket to our if statement
so LB Web Apps were always marked as not HTTPS because
the HTTPS Struct was being redefined.
Note, we need to add some tests for this 100%.
This is for an app that uses HTTPS: 
`copilot svc package --output-dir infra`
Before:
```json
{
"Parameters" : { 
...
"HTTPSEnabled": "false"
},
"Tags": { 
...
}
}
```
After:
```json
{
"Parameters" : { 
...
"HTTPSEnabled": "true"
},
"Tags": { 
...
}
}
```
> fix: HTTPS Params in "svc package" was always false

- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/svc_deploy.go
- internal/pkg/docker/docker.go
- internal/pkg/docker/docker_test.go
This PR adds support for building and pushing images with multiple tagging, while keeping the original build/push intact.
> chore(docker): add support for multiple tagging to docker pkg

- internal/pkg/cli/env_show.go
> feat(cli): enable "env show" command

- internal/pkg/aws/ecr/ecr.go
- internal/pkg/aws/ecr/ecr_test.go
- internal/pkg/cli/init.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/svc_deploy.go
This PR contains the following changes:
1. refactor `ecr` package to change method signatures of `GetECRAuth(Auth, error)` to `Auth(string,string,error)` and `GetRepository(name string)(string,error)` to `RepositoryURI(name string)(string,error)` 
2. refactor `cli` package to use `repository` pkg (related PR #1161)
> chore(cli): refactor cli to use repository pkg

- internal/pkg/cli/task_run.go
- internal/pkg/cli/task_run_test.go
This PR implements `Execute` for `task run`
> chore(cli): deploy and update task resources for `task run`

- internal/pkg/aws/ecs/ecs.go
- internal/pkg/aws/ecs/ecs_test.go
This PR adds a method to `ecs` package that describes tasks given a cluster and task ARNs. This is to support `--follow` flag for `task run`.
> chore(ecs): describe tasks given a cluster and task ARNs

- internal/pkg/cli/task_run.go
- internal/pkg/cli/task_run_test.go
This PR builds and pushes image and updates image to task definition for `task run`. This is a part of the series of PRs that implement `Execute` for `task run`. 
Related #702 
> chore(cli): update image to task for `task run`

- site/content/en/docs/Commands/svc/init.md
current: $ copilot svc init --name frontend **--app-type** "Load Balanced Web Service" --dockerfile ./frontend/Dockerfile
suggest: $ copilot svc init --name frontend **--svc-type** "Load Balanced Web Service" --dockerfile ./frontend/Dockerfile
--app-type option does not exist. --svc-type is correct.
> docs: correct option name for example command.

- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/task_run.go
- internal/pkg/cli/task_run_test.go
This PR starts the task(s) for `task run`. This is a part of the series of PRs that implement Execute for task run.
Related #702
> chore(cli): start tasks for `task run`

- site/content/en/docs/Commands/env/_index.md
- site/content/en/docs/Commands/env/delete.md
- site/content/en/docs/Commands/env/show.md
Wiki page has the document for `copilot env show` command, but there is no file related to it in this repository. Adding markdown based on wiki's one. Also, wiki page includes wrong explanation.
current: `copilot env ls` shows info about a deployed environment, including region, account ID, and services.
suggest: `copilot env show` shows info about a deployed environment, including region, account ID, and services.
`copilot env ls` is another sub command. `copilot env show` is correct.
> docs(site): add missing document for "env show" command 

- Makefile
Remove -race from go build because it could increase memory usage by 5-10x and execution time by 2-20x. https://golang.org/doc/articles/race_detector.html#Runtime_Overheads
> perf(makefile): remove -race for go build

- internal/pkg/aws/session/session.go
Setting SharedConfigState to SharedConfigEnable allows the AWS SDK to
load the shared config file (~/.aws/config). Previously, we were
ignoring the config file for the "DefaultWithRegion" method hence why it
wouldn't pick up the credentials_process field in the file.
Fixes #808
> fix(session): set SharedConfigEnable for DefaultWithRegion

- site/content/en/docs/Commands/pipeline/delete.md
- site/content/en/docs/Commands/pipeline/show.md
- site/content/en/docs/Commands/pipeline/status.md
Wiki page has the document for `copilot pipeline show` and `copilot pipeline status` command, but there is no file related to them in this repository. Adding markdown based on wiki's one.
> docs(site): add missing document for "pipeline show/status" command

- e2e/internal/client/cli.go
- e2e/multi-env-app/multi_env_test.go
- internal/pkg/deploy/cloudformation/app.go
- templates/app/cf.yml
There seems to be an issue with the current KMS CF resource
that is causing superfluous tag/untag calls. This new permission
fixes that issue.
A customer encountered this issue (#1199) when using resource tags,
so I've also updated the e2e tests to include setting resource tags.
In the future, this permission will be useful if we want to support
updating tags at the app level (removing a tag, for example) so it's
not entierly a hack :)
Fixes #1199 
> fix: add UntagResource permission for KMS key

- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/task_run.go
- internal/pkg/cli/task_run_test.go
- internal/pkg/term/selector/selector.go
This PR contains the following change:
1. refactor selector to extend `Application` to accept additional options passed from `cli`
2. ask for application in `task run` if no workspace is found and no app flag is provided
> chore(selector): extend `Application` to accept additional options passed from `cli`

- internal/pkg/cli/pipeline_init.go
- site/content/en/docs/Commands/pipeline/init.md
`copilot pipeline init -h` shows the example command with unused option "--deploy". This PR removes it.
Related #1202
> chore(cli): remove unused option --deploy from example for "pipeline init".

- Makefile
- buildspec.yml
This change produces ARM binaries for Linux. We can't enable
the same for our darwin builds right now since go assumes that
darwin/arm64 is an iOS target:
https://github.com/golang/go/issues/38485
This fixes #1058
> feat: ARM64 build target for linux

- go.mod
- go.sum
- internal/pkg/aws/ec2/ec2.go
- internal/pkg/aws/ec2/ec2_test.go
Part of #1192.
1. Add `ListVpcSubnets` to list all subnets given a VPC ID.
2. Add pagination when calling `DescribeSubnets` so that we won't miss results in following pages.
> chore(ec2): add ListVpcSubnets method and pagination

- README.md
`/aws/copilot-cli` throws a 404.
`/aws/amazon-ecs-cli-v2` works much better.
> chore(readme): fixed gitter url

- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/task_run.go
- internal/pkg/cli/task_run_test.go
- internal/pkg/deploy/cloudformation/task.go
- templates/environment/cf/environment-manager-role.yml
This PR contains the following changes:
1. Update environment manager role's permission in support of `task run`
2. Update `task run` to use environment manager
> chore: update `task run` to use manager roles and update manager permissions

- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/flag.go
- internal/pkg/cli/init.go
- Add the struct to hold temporary credentials.
- Validate temp credentials flags.
- Create clients from temporary credentials if specified.
The PR to ask for the credentials, updating `env delete`, and `env init` will be follow-ups.
Related #1228 
> chore(cli): enable creating environments from temporary creds

- internal/pkg/cli/init.go
The new `unmarshal` field was missing in init resulting in a segfault.
> chore(cli): fix deploying a svc from "init" with new docker build args

- internal/pkg/aws/ecs/ecs.go
- internal/pkg/aws/ecs/ecs_test.go
- internal/pkg/cli/interfaces.go
- internal/pkg/cli/mocks/mock_interfaces.go
- internal/pkg/cli/task_run.go
- internal/pkg/cli/task_run_test.go
This PR contains the following changes:
1. implement `HasDefaultCluster` in `ecs` package
2. early check for default cluster in `task run`
> chore: early check for default cluster in `task run`

- internal/pkg/aws/ecs/ecs.go
- internal/pkg/aws/ecs/errors.go
This PR refactors `RunTask` method from `ecs` package to return more informative error message. 
The error message returned from the waiter is too generic. For example, currently the error message eventually returned to the user may look like this:
```
✘ run task test: run task test: wait for tasks to be running: ResourceNotReady: failed waiting for successful resource state
```
When the waiter fails to wait for the tasks to start, if it's a `ResourceNotReady` error, we try to return the container-level failure reason, which is more informative. For example, the error message may look like this:
```
✘ run task test: run task test: task 590bc4fe: CannotStartContainerError: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused …
```
> chore(ecs): return container stopped reason from RunTask

- e2e/task/task_test.go
The e2e tests fail now because we cannot specify both a copilot application and the default cluster while running a task.
This change runs the test only using the default cluster.
> test(e2e): fix task run test with overrides

- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
This PR fixes `env init` by removing redundant prompt that asks users to select if they'd like to adjust/import/use default, even if users have already specified any of import/config flag set.
> fix(cli): remove env init redundant prompt

- internal/pkg/cli/svc_deploy.go
- internal/pkg/cli/svc_package.go
- internal/pkg/cli/svc_package_test.go
- internal/pkg/term/prompt/prompt.go
- internal/pkg/term/selector/creds.go
- internal/pkg/term/selector/creds_test.go
Previously, when the `validators` param was `nil`, the `prompt` pkg automatically added the `survey.Required` validator.
This change makes validation optional, and if we want to make a prompt's answer required we can use the new `prompt.RequireNonEmpty` function.
> chore(prompt): make validation optional for Get prompt

- internal/pkg/cli/env_init.go
- internal/pkg/cli/env_init_test.go
- internal/pkg/cli/flag.go
This PR
1. Change the selection order in env init.
2. Update default flag in env init from `--no-customized-env` to `--default-config`
> chore(cli): change env init selection order and default flag change

- e2e/task/task_suite_test.go
Currently our task e2e test doesn't delete the task stack after running the task e2e test. And the task stack is very difficult to remove because the CFN Execution Role that used to manage the task stack is deleted when we delete copilot environment.  Also, the remaining task stacks piles up in our Copilot pipeline account.
This PR fixes this issue by removing task stack before we delete copilot app/env.
> test(e2e): clean redundant task stack for task e2e test
